DROP SCHEMA IF EXISTS plantzzz;
CREATE DATABASE plantzzz;
USE plantzzz;

DROP TABLE IF EXISTS plant;
CREATE TABLE plant (
  id INT NOT NULL AUTO_INCREMENT,
  academic_name VARCHAR(255) NOT NULL,
  daily_name VARCHAR(255) NOT NULL,
  description VARCHAR(1000) NOT NULL DEFAULT 'Oops! Nothing is here ...',
  is_active BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS picture;
CREATE TABLE picture (
id INT NOT NULL AUTO_INCREMENT,
picture_file_name VARCHAR(255) NOT NULL,
plant_id INT NOT NULL,
is_active BOOLEAN DEFAULT TRUE,
PRIMARY KEY (id),
FOREIGN KEY (plant_id) REFERENCES plant(id)
);

DROP TABLE IF EXISTS user_type;
CREATE TABLE user_type (
id INT NOT NULL AUTO_INCREMENT,
type_name VARCHAR(255) NOT NULL,
is_active BOOLEAN DEFAULT TRUE,
PRIMARY KEY (id)
);

DROP TABLE IF EXISTS user;
CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  user_type INT NOT NULL,
  score INT NOT NULL DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (id),
  FOREIGN KEY (user_type) REFERENCES user_type(id)
);

DROP TABLE IF EXISTS plant_remembered;
CREATE TABLE plant_remembered (
  user_id INT NOT NULL,
  plant_id INT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (user_id, plant_id),
  FOREIGN KEY (user_id) REFERENCES user(id),
  FOREIGN KEY (plant_id) REFERENCES plant(id)
);

DROP TABLE IF EXISTS product_type;
CREATE TABLE product_type (
id INT NOT NULL AUTO_INCREMENT,
type_name VARCHAR(255) NOT NULL,
is_active BOOLEAN DEFAULT TRUE,
PRIMARY KEY (id)
);

DROP TABLE IF EXISTS product;
CREATE TABLE product (
  id INT NOT NULL AUTO_INCREMENT,
  product_name VARCHAR(255) NOT NULL,
  product_type INT NOT NULL,
  price INT NOT NULL,
  picture VARCHAR(255) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (id),
  FOREIGN KEY (product_type) REFERENCES product_type(id)
);

DROP TABLE IF EXISTS purchase;
CREATE TABLE purchase (
user_id INT NOT NULL,
product_id INT,
quantity INT NOT NULL DEFAULT 1,
PRIMARY KEY (user_id, product_id),
FOREIGN KEY (user_id) REFERENCES user(id),
FOREIGN KEY (product_id) REFERENCES product(id)
);

DROP TABLE IF EXISTS garden;
CREATE TABLE garden (
user_id INT NOT NULL,
garden_state TEXT NOT NULL,
PRIMARY KEY (user_id),
FOREIGN KEY (user_id) REFERENCES user(id)
	ON DELETE CASCADE
);

INSERT INTO user_type (type_name, is_active) VALUES
('Admin', 1),
('Student', 1);

INSERT INTO user (username, email, password, user_type, score, is_active) VALUES
('CallieZheng', 'Calliezheng233@gmail.com', '$2b$12$pM3cuZeVWhPMFSIUTes07.0TfiVOHhFD0MLQLeoxPiWb571cZc19u', 2, 10000, 1),
('PixelPioneer', 'PixelPioneer@mail.com', '$2b$12$O.f8VRMICUWK83Xqxe2UQe9jYfOAIU5EeykhaXt64eN2RF2IR6bzG', 2, 0, 1),
('EchoSage', 'EchoSage@example.com', '$2b$12$gzj9cCuaEb5rK5NVrHxrbeSJ0ZqSqUg9RizXdxNZj08LPMLkH3iiW', 2, 0, 1),
('FrostVoyager', 'FrostVoyager@mail.com', '$2b$12$C.Bn8WoC9XBDeoitkwh9fuUS7lv9E9t7/kNE8Cd9M5MyPnE70kISe', 2, 0, 1),
('Admin', 'Calliezheng@hotmail.com', '$2b$12$x8YaY8C5g4EW.FHqPz2eoOGYeL4GyO1X6H8C5ocnprExSOUs2a4hm', 1, 0, 1),
('Admin1', 'Staff1@hotmail.com', '$2b$12$x8YaY8C5g4EW.FHqPz2eoOGYeL4GyO1X6H8C5ocnprExSOUs2a4hm', 1, 0, 1),
('Admin2', 'Staff2@hotmail.com', '$2b$12$x8YaY8C5g4EW.FHqPz2eoOGYeL4GyO1X6H8C5ocnprExSOUs2a4hm', 1, 0, 1);

INSERT INTO plant (academic_name, daily_name, is_active) VALUES
("Acaena inermis _Purpurea_", 'purple bidibid', 1),
("Acanthus mollis", 'bears breeches', 1),
("Acca sellowiana", 'feijoa', 1),
("Acer griseum", 'paperbark maple', 1),
("Acer palmatum", 'Japanese maple', 1),
("Acer palmatum _Senkaki_", 'coral bark maple', 1),
("Acer platanoides", 'Norway maple', 1),
("Aciphylla dieffenbachii", 'Chatham Island spaniard', 1),
("Aesculus hippocastanum", 'common horse chestnut', 1),
("Agapanthus africanus", 'agapanthus', 1),
("Agathis australis", 'kauri', 1),
("Agave sp.", 'agave', 1),
("Alectryon excelsus", 'titoki', 1),
("Alnus glutinosa", 'black alder', 1),
("Alstroemeria spp.", 'Peruvian Lily', 1),
("Anemanthele lessoniana", 'wind grass', 1),
("Anigozanthos flavidus", 'kangaroo paw', 1),
("Apodasmia similis", 'oioi', 1),
("Aquilegia sp.", 'Granny_s Bonnet', 1),
("Arbutus unedo", 'strawberry tree', 1),
("Aristotelia serrata", 'winberry or makomako', 1),
("Arthropodium cirratum", 'rengarenga', 1),
("Asplenium bulbiferum", 'Hen and Chiken Fern', 1),
("Asplenium oblongifolium", 'shining spleenwort', 1),
("Astelia chathamica", 'Chatham Islands astelia', 1),
("Aucuba japonica", 'spotted or Japanese laurel', 1),
("Austroderia richardii", 'South Island toe toe', 1),
("Azara microphylla", 'vanilla tree', 1),
("Banksia integrifolia", 'coastal banksia', 1),
("Bergenia cordifolia", 'heart leaf bergenia', 1),
("Betula pendula", 'silver birch', 1),
("Blechnum discolor", 'Crown Fern', 1),
("Brachychiton populneus", 'kurrajong or bottletree', 1),
("Brachyglottis greyi", 'NZ daisy bush', 1),
("Brachyglottis monroi", 'Monro_s daisy', 1),
("Brachyglottis rotundifolia", 'muttonbird scrub', 1),
("Buxus sempervirens", 'box hedge', 1),
("Callistemon sp.", 'bottle brush', 1),
("Camellia japonica", 'Japanese camelia', 1),
("Camellia sasanqua", 'autumn camellia', 1),
("Canna X generalis", 'canna lily', 1),
("Carex secta", 'pukio', 1),
("Carex testacea", 'orange sedge', 1),
("Carmichaelia appressa", 'native prostrate broom', 1),
("Carmichaelia australis", 'NZ Native Broom', 1),
("Carmichaelia stevensonii", 'weeping broom', 1),
("Carmichaelia williamsii", 'NZ giant flowering broom', 1),
("Carpinus betulus", 'European hornbeam', 1),
("Carpodetus serratus", 'marble leaf or putaputaweta', 1),
("Catalpa bignonioides", 'Indian bean tree', 1),
("Celmisia sp.", 'mountain daisy', 1),
("Cercis canadensis _Texas White_", 'Texas white redbud', 1),
("Chamaecytisus palmensis", 'Tree Lucerne', 1),
("Chimonanthus praecox", 'wintersweet', 1),
("Chionochloa flavicans", 'miniature toetoe', 1),
("Chionochloa rubra", 'Red Tussock', 1),
("Choisya ternata", 'Mexican orange blossom', 1),
("Choisya X dewitteana _Aztec Pearl", 'Mexican orange blossom', 1),
("Clematis afoliata", 'Leafless Clematis', 1),
("Clematis paniculata", 'puawhananga', 1),
("Clianthus maximus", 'kakabeak', 1),
("Clivia sp.", 'natal or bush lily', 1),
("Coleonema pulchrum _Sunset Gold_", 'confetti bush', 1),
("Convolvulus cneorum", 'morning glory or silverbush', 1),
("Coprosma acerosa _Hawera_", 'Hawera sand coprosma', 1),
("Coprosma _Black Cloud_", 'Black Cloud Coprosma', 1),
("Coprosma propinqua", 'mingimingi', 1),
("Coprosma repens", 'mlrror bush or taupata', 1),
("Coprosma rugosa _Lobster_", 'red coprosma', 1),
("Coprosma X kirkii", 'groundcover coprosma', 1),
("Cordyline australis", 'cabbage tree', 1),
("Cornus alba", 'Siberian dogwood', 1),
("Cornus florida", 'dogwood', 1),
("Corokia X virgata _Bronze King_", 'bronze corokia', 1),
("Corylus avellana", 'common hazel', 1),
("Corynocarpus laevigatus", 'karaka or NZ laurel', 1),
("Cotinus coggygria", 'smoke bush', 1),
("Cotoneaster horizontalis", 'rock spray', 1),
("Cupressus macrocarpa", 'macrocarpa', 1),
("Cupressus sempervirens", 'Italian cypress', 1),
("Cyclamen hederifolium", 'ivy leaved cyclamen', 1),
("Cytisus proliferus", 'tree lucerne or tagasaste', 1),
("Dacrydium cupressinum", 'rimu', 1),
("Daphne bholua", 'Nepalese paper plant', 1),
("Daphne odora", 'winter daphne', 1),
("Dianella nigra", 'turutu', 1),
("Dianella sp. _Little Rev_ ", 'dianella', 1),
("Dianella tasmania _Blaze_", 'Dianella', 1),
("Dicksonia squarrosa", 'wheki or rough tree fern', 1),
("Discaria toumatou", 'matagouri', 1),
("Disphyma australe", 'horokaka or native ice plant', 1),
("Dodonaea viscosa _Purpurea_", 'akeake or hopbush', 1),
("Dracophyllum sinclairii", 'inaka or neinei', 1),
("Echium candicans", 'pride of Madeira', 1),
("Eucalyptus viminalis", 'manna gum', 1),
("Euphorbia glauca", 'shore spurge or waiu-atua', 1),
("Fagus sylvatica", 'common or English beech', 1),
("Fatsia japonica", 'Japanese Aralia', 1),
("Festuca actae", 'Banks Peninsula blue tussock', 1),
("Ficus pumila", 'creeping fig', 1),
("Fraxinus excelsior", 'European or common ash', 1),
("Fuchsia procumbens", 'creeping fuchsia', 1),
("Fuscospora cliffortioides", 'mountain beech', 1),
("Fuscospora fusca", 'red beech', 1),
("Fuscospora solandri", 'black beech', 1),
("Garrya elliptica", 'Silk Tassel Bush', 1),
("Ginkgo biloba", 'maidenhair tree', 1),
("Grevillea banksii X bipinnatifida", 'grevillea', 1),
("Griselinia littoralis", 'broadleaf or kapuka', 1),
("Haloregis erecta _Purpurea_", 'toatoa', 1),
("Hamamelis mollis", 'witch hazel', 1),
("Heliohebe hulkeana", 'New Zealand lilac', 1),
("Helleborus argutifolius", 'Corsican hellebore', 1),
("Helleborus foetidus", 'Stinking Hellebore', 1),
("Helleborus orientalis", 'lenten rose', 1),
("Hoheria angustifolia", 'narrow leaved lacebark', 1),
("Hoheria lyallii", 'mountain lacebark', 1),
("Hoheria sexstylosa", 'lacebark or houhere', 1),
("Hydrangea macrophylla", 'mophead hydrangea', 1),
("Hydrangea paniculata", 'panicled hydrangea', 1),
("Hydrangea quercifolia _Pee Wee_", 'oak leaf hydrangea', 1),
("Ilex aquifolium", 'English holly', 1),
("Juncus pallidus", 'giant club rush', 1),
("Knightia excelsa", 'rewarewa (NZ honeysuckle)', 1),
("Kunzea ericoides", 'kanuka', 1),
("Laurus nobilis", 'bay tree', 1),
("Lavandula X intermedia", 'hybrid lavender', 1),
("Leonohebe cupressoides", 'frangrant hebe', 1),
("Leucadendron argenteum", 'Silver Tree', 1),
("Leucadendron salignum", 'conebush', 1),
("Libertia ixioides", 'NZ iris or mikoikoi', 1),
("Libertia peregrinans", 'NZ iris', 1),
("Liquidambar styraciflua", 'American sweetgum', 1),
("Liriodendron tulipifera", 'tulip tree', 1),
("Lomandra longifolia", 'basket grass', 1),
("Lomaria discolor", 'crown fern', 1),
("Lophomyrtus obcordata", 'rohutu or NZ myrtle', 1),
("Lophomyrtus x ralphii", 'hybrid lophomyrtus or NZ myrtle', 1),
("Lophozonia menziesii", 'silver beech', 1),
("Magnolia grandiflora _Little Gem_", 'dwarf magnolia', 1),
("Magnolia liliflora _Nigra_", 'deciduous magnolia', 1),
("Magnolia X soulangeana", 'saucer or Chinese magnolia', 1),
("Malus sp.", 'apple tree', 1),
("Melicytus alpinus", 'porcupine scrub', 1),
("Melicytus lanceolatus", 'Narrow Leaved Mahoe', 1),
("Melicytus ramiflorus", 'mahoe or whiteywood', 1),
("Metrosideros umbellata", 'Southern Rata', 1),
("Michelia yunnanensis", 'evergreen michelia', 1),
("Microleana avenacea", 'bush rice grass', 1),
("Muehlenbeckia astonii", 'shrubby tororaro', 1),
("Muehlenbeckia australis", 'pohuehue', 1),
("Muehlenbeckia axillaris", 'creeping muehlenbeckia', 1),
("Muehlenbeckia complexa", 'small-leaved pohuehue', 1),
("Myoporum laetum", 'ngaio', 1),
("Myosotidium hortensia", 'Chatham Island forget me not', 1),
("Nandina domestica 'Pygmaea'", 'dwarf heavenly bamboo', 1),
("Narcissus sp.", 'Daffodil', 1),
("Nepeta mussinii", 'cat mint', 1),
("Olea europaea", 'olive tree', 1),
("Olearia cheesemanii", 'NZ daisy bush', 1),
("Olearia lineata", 'twiggy tree daisy', 1),
("Olearia paniculata", 'Golden Akeake or Akiraho', 1),
("Olearia X macrodonta", 'NZ or Mountain Holly', 1),
("Ophiopogon planiscapus _Black Dragon_", 'black mondo grass', 1),
("Ozothamnus leptophylllus", 'Cottonwood or Tauhinu', 1),
("Pachysandra terminalis", 'Japanese spurge', 1),
("Pachystegia insignis", 'Malborough rock daisy', 1),
("Pachystegia rufa", 'Marlborough rock daisy', 1),
("Pectinopitys ferruginea", 'miro', 1),
("Phebalium squameum", 'satinwood', 1),
("Phormium cookianum", 'wharariki or mountain Flax', 1),
("Phormium tenax", 'harakeke or NZ flax', 1),
("Photinia X fraseri _Robusta_", 'photinia', 1),
("Phyllocladus alpinus", 'mountain toatoa or celery pine', 1),
("Phyllocladus trichomanoides", 'tenakaha', 1),
("Pieris japonica", 'lily of the valley', 1),
("Pimelea prostrata", 'NZ daphne', 1),
("Piper excelsum", 'kawakawa', 1),
("Pittosporum crassifolium", 'karo', 1),
("Pittosporum eugenioides", 'lemonwood or tarata', 1),
("Pittosporum patulum", 'Pitpat', 1),
("Pittosporum tenuifolium", 'kohuhu or black matipo', 1),
("Pittosporum tenuifolium _Sumo_", 'dwarf pittosporum', 1),
("Plagianthus divarivatus", 'swamp ribbonwood', 1),
("Plagianthus regius", 'lowland ribbonwood', 1),
("Platanus orientalis _Digitata_", 'cut leaf plane', 1),
("Platanus x acerifolia", 'London plane', 1),
("Poa cita", 'silver tussock', 1),
("Podocarpus laetus", 'mountain or Hall_s totara', 1),
("Podocarpus nivalis", 'snow or mountain totara', 1),
("Podocarpus totara", 'totara', 1),
("Polyspora axillaris", 'fried egg plant', 1),
("Polystichum vestitum", 'prickly shield fern or puniu', 1),
("Populus trichocarpa", 'black cottonwood', 1),
("Pratia (syn. Lobelia) angulata", 'panakenake', 1),
("Protea neriifolia", 'oleanderleaf protea', 1),
("Prumnopitys taxifolia", 'matai', 1),
("Prunus laurocerasus", 'cherry laurel', 1),
("Prunus lusitanica", 'Portuguese Cherry Laurel', 1),
("Prunus x yedoensis", 'Yoshino cherry', 1),
("Pseudopanax lessonii", 'houpara', 1),
("Pseudopanax crassifolius", 'lancewood', 1),
("Pseudopanax ferox", 'fierce lancewood', 1),
("Pseudowintera colorata", 'horopito or pepper tree', 1),
("Pyrus communis", 'common pear', 1),
("Quercus palustris", 'pin oak', 1),
("Quercus robur", 'English oak', 1),
("Quercus rubra", 'red oak', 1),
("Rhododendron sp.", 'azalea', 1),
("Rhododendron sp.", 'rhododendron', 1),
("Rhopalostylis sapida", 'nikau palm', 1),
("Robinia pseudoacacia _Lace Lady_", 'contoured black locust', 1),
("Rosa sp. _Ivey Hall_", 'yellow floribunda rose', 1),
("Rosmarinus officinalis", 'rosemary', 1),
("Rubus cissoides", 'bush lawyer', 1),
("Salvia officinalis", 'common sage', 1),
("Santolina chamaecyparissus", 'lavender cotton', 1),
("Sarcococca confusa", 'sweet box', 1),
("Scleranthus biflorus", 'knawel cushion or cushion plant', 1),
("Sedum spectabile _Autumn Joy_", 'stonecrop', 1),
("Sequoia sempervirens", 'redwood', 1),
("Skimmia japonica", 'Japanese skimmia', 1),
("Solanum laciniatum", 'poroporo', 1),
("Sophora microphylla", 'South Island kowhai', 1),
("Sophora molloyi _Dragons Gold_", 'Cook Strait kowhai', 1),
("Sophora prostrata", 'prostrate kowhai', 1),
("Sophora tetraptera", 'North Island kowhai', 1),
("Sorbus aucuparia", 'rowan', 1),
("Teucridium parvifolium", 'teucridium', 1),
("Tilia cordata", 'lime tree', 1),
("Tilia vulgaris", 'Lime Tree', 1),
("Trachycarpus fortunei", 'Chinese Windmill Palm_', 1),
("Typha orientalis", 'raupo or bullrush', 1),
("Ulmus carpinifolia _Variegata_", 'variegated elm', 1),
("Veronica _Emerald Green_", 'Whipcord Hebe', 1),
("Veronica hulkeana", 'New Zeland lilac', 1),
("Veronica odora _Prostrata_", 'prostrate hebe', 1),
("Veronica salicifolia", 'Koromiko', 1),
("Veronica sp. _Wiri MIst_", 'Wiri Mist Hebe', 1),
("Veronica speciosa", 'large leaved hebe', 1),
("Veronica topiaria", 'topiary hebe', 1),
("Viburnum japonicum", 'Japanese Viburnum', 1),
("Viburnum tinus", 'laurustinus', 1),
("Wisteria sinensis", 'Chinese wisteria', 1),
("Zantedeschia aethiopica", 'arum or calla Lily', 1);

INSERT INTO picture (picture_file_name, plant_id, is_active) VALUES
('Acaena inermis _Purpurea_ - purple bidibid.jpg', 1, 1),
('Acaena inermis _Purpurea_ - purple bidibid2.jpeg', 1, 1),
('Acaena inermis _Purpurea_ - purple bidibid3.jpg', 1, 1),
('Acanthus mollis - bears breeches.jpg', 2, 1),
('Acanthus mollis - bears breeches2.jpeg', 2, 1),
('Acanthus mollis - bears breeches3.jpeg', 2, 1),
('Acca sellowiana - feijoa.jpg', 3, 1),
('Acca sellowiana - feijoa2.jpeg', 3, 1),
('Acca sellowiana - feijoa3.jpg', 3, 1),
('Acer griseum - paperbark maple.jpg', 4, 1),
('Acer griseum - paperbark maple2.jpg', 4, 1),
('Acer griseum - paperbark maple3.jpg', 4, 1),
('Acer palmatum - Japanese maple.jpg', 5, 1),
('Acer palmatum - Japanese maple2.jpg', 5, 1),
('Acer palmatum - Japanese maple3.jpeg', 5, 1),
('Acer palmatum _Senkaki_ - coral bark maple.jpg', 6, 1),
('Acer palmatum _Senkaki_ - coral bark maple2.jpg', 6, 1),
('Acer palmatum _Senkaki_ - coral bark maple3.jpg', 6, 1),
('Acer platanoides - Norway maple.jpg', 7, 1),
('Acer platanoides - Norway maple2.jpg', 7, 1),
('Acer platanoides - Norway maple3.jpg', 7, 1),
('Aciphylla dieffenbachii - Chatham Island spaniard.jpg', 8, 1),
('Aciphylla dieffenbachii - Chatham Island spaniard2.jpg', 8, 1),
('Aciphylla dieffenbachii - Chatham Island spaniard3.jpg', 8, 1),
('Aesculus hippocastanum - common horse chestnut.jpg', 9, 1),
('Aesculus hippocastanum - common horse chestnut2.jpeg', 9, 1),
('Aesculus hippocastanum - common horse chestnut3.jpeg', 9, 1),
('Aesculus hippocastanum - common horse chestnut4.jpg', 9, 1),
('Aesculus hippocastanum - common horse chestnut5.jpeg', 9, 1),
('Aesculus hippocastanum - common horse chestnut6.jpg', 9, 1),
('Aesculus hippocastanum - common horse chestnut7.jpeg', 9, 1),
('Aesculus hippocastanum - common horse chestnut8.jpg', 9, 1),
('Agapanthus africanus - agapanthus.jpg', 10, 1),
('Agapanthus africanus - agapanthus2.jpg', 10, 1),
('Agapanthus africanus - agapanthus3.jpg', 10, 1),
('Agapanthus africanus - agapanthus4.jpg', 10, 1),
('Agapanthus africanus - agapanthus5.jpeg', 10, 1),
('Agathis australis - kauri.jpg', 11, 1),
('Agathis australis - kauri2.jpg', 11, 1),
('Agathis australis - kauri3.jpg', 11, 1),
('Agathis australis - kauri4.jpg', 11, 1),
('Agave sp. - agave.jpeg', 12, 1),
('Agave sp. - agave2.webp', 12, 1),
('Agave sp. - agave3.jpeg', 12, 1),
('Agave sp. - agave4.jpeg', 12, 1),
('Alectryon excelsus - titoki.jpg', 13, 1),
('Alectryon excelsus - titoki2.jpg', 13, 1),
('Alectryon excelsus - titoki3.jpg', 13, 1),
('Alectryon excelsus - titoki4.jpg', 13, 1),
('Alectryon excelsus - titoki5.jpg', 13, 1),
('Alnus glutinosa - black alder.jpeg', 14, 1),
('Alnus glutinosa - black alder2.jpeg', 14, 1),
('Alnus glutinosa - black alder3.jpeg', 14, 1),
('Alstroemeria spp. - Peruvian Lily.jpg', 15, 1),
('Alstroemeria spp. - Peruvian Lily2.jpg', 15, 1),
('Alstroemeria spp. - Peruvian Lily3.jpg', 15, 1),
('Alstroemeria spp. - Peruvian Lily4.jpg', 15, 1),
('Alstroemeria spp. - Peruvian Lily5.jpg', 15, 1),
('Alstroemeria spp. - Peruvian Lily6.jpg', 15, 1),
('Alstroemeria spp. - Peruvian Lily7.jpg', 15, 1),
('Anemanthele lessoniana - wind grass.jpeg', 16, 1),
('Anemanthele lessoniana - wind grass2.jpeg', 16, 1),
('Anemanthele lessoniana - wind grass3.jpg', 16, 1),
('Anigozanthos flavidus - kangaroo paw.jpeg', 17, 1),
('Anigozanthos flavidus - kangaroo paw2.webp', 17, 1),
('Anigozanthos flavidus - kangaroo paw3.jpeg', 17, 1),
('Apodasmia similis - oioi.jpg', 18, 1),
('Apodasmia similis - oioi2.jpg', 18, 1),
('Apodasmia similis - oioi3.jpg', 18, 1),
('Aquilegia sp. - Granny_s Bonnet.jpg', 19, 1),
('Aquilegia sp. - Granny_s Bonnet2.jpg', 19, 1),
('Aquilegia sp. - Granny_s Bonnet3.jpg', 19, 1),
('Aquilegia sp. - Granny_s Bonnet4.jpg', 19, 1),
('Aquilegia sp. - Granny_s Bonnet5.jpg', 19, 1),
('Aquilegia sp. - Granny_s Bonnet6.jpg', 19, 1),
('Aquilegia sp. - Granny_s Bonnet7.jpeg', 19, 1),
('Arbutus unedo - strawberry tree.jpg', 20, 1),
('Arbutus unedo - strawberry tree2.jpg', 20, 1),
('Arbutus unedo - strawberry tree3.jpg', 20, 1),
('Arbutus unedo - strawberry tree4.jpg', 20, 1),
('Arbutus unedo - strawberry tree5.jpg', 20, 1),
('Arbutus unedo - strawberry tree6.jpg', 20, 1),
('Arbutus unedo - strawberry tree7.jpg', 20, 1),
('Arbutus unedo - strawberry tree8.jpg', 20, 1),
('Aristotelia serrata - winberry or makomako.jpg', 21, 1),
('Aristotelia serrata - winberry or makomako2.jpg', 21, 1),
('Aristotelia serrata - winberry or makomako3.jpg', 21, 1),
('Aristotelia serrata - winberry or makomako4.jpg', 21, 1),
('Aristotelia serrata - winberry or makomako5.jpg', 21, 1),
('Arthropodium cirratum - rengarenga.jpeg', 22, 1),
('Arthropodium cirratum - rengarenga2.jpeg', 22, 1),
('Arthropodium cirratum - rengarenga3.jpg', 22, 1),
('Arthropodium cirratum - rengarenga4.jpg', 22, 1),
('Asplenium bulbiferum - Hen and Chiken Fern.jpg', 23, 1),
('Asplenium bulbiferum - Hen and Chiken Fern2.jpg', 23, 1),
('Asplenium bulbiferum - Hen and Chiken Fern3.jpg', 23, 1),
('Asplenium bulbiferum - Hen and Chiken Fern4.jpg', 23, 1),
('Asplenium oblongifolium - shining spleenwort.jpg', 24, 1),
('Asplenium oblongifolium - shining spleenwort2.jpg', 24, 1),
('Asplenium oblongifolium - shining spleenwort3.jpg', 24, 1),
('Astelia chathamica - Chatham Islands astelia.jpg', 25, 1),
('Astelia chathamica - Chatham Islands astelia2.jpg', 25, 1),
('Astelia chathamica - Chatham Islands astelia3.jpg', 25, 1),
('Aucuba japonica - spotted or Japanese laurel.jpg', 26, 1),
('Aucuba japonica - spotted or Japanese laurel2.jpg', 26, 1),
('Aucuba japonica - spotted or Japanese laurel3.jpeg', 26, 1),
('Aucuba japonica - spotted or Japanese laurel4.jpg', 26, 1),
('Aucuba japonica - spotted or Japanese laurel5.jpg', 26, 1),
('Austroderia richardii - South Island toe toe.jpg', 27, 1),
('Austroderia richardii - South Island toe toe2.jpeg', 27, 1),
('Austroderia richardii - South Island toe toe3.jpg', 27, 1),
('Azara microphylla - vanilla tree.jpg', 28, 1),
('Azara microphylla - vanilla tree2.jpg', 28, 1),
('Azara microphylla - vanilla tree3.jpg', 28, 1),
('Banksia integrifolia - coastal banksia.jpg', 29, 1),
('Banksia integrifolia - coastal banksia2.jpg', 29, 1),
('Banksia integrifolia - coastal banksia3.jpg', 29, 1),
('Banksia integrifolia - coastal banksia4.jpg', 29, 1),
('Banksia integrifolia - coastal banksia5.jpg', 29, 1),
('Bergenia cordifolia - heart leaf bergenia.jpg', 30, 1),
('Bergenia cordifolia - heart leaf bergenia2.jpg', 30, 1),
('Bergenia cordifolia - heart leaf bergenia3.jpg', 30, 1),
('Bergenia cordifolia - heart leaf bergenia4.jpeg', 30, 1),
('Betula pendula - silver birch.jpg', 31, 1),
('Betula pendula - silver birch2.jpg', 31, 1),
('Betula pendula - silver birch3.jpg', 31, 1),
('Betula pendula - silver birch4.jpg', 31, 1),
('Blechnum discolor - Crown Fern.jpg', 32, 1),
('Blechnum discolor - Crown Fern2.jpg', 32, 1),
('Blechnum discolor - Crown Fern3.jpg', 32, 1),
('Blechnum discolor - Crown Fern4.jpg', 32, 1),
('Blechnum discolor - Crown Fern5.jpg', 32, 1),
('Brachychiton populneus - kurrajong or bottletree.jpeg', 33, 1),
('Brachychiton populneus - kurrajong or bottletree2.jpg', 33, 1),
('Brachyglottis greyi - NZ daisy bush.jpg', 34, 1),
('Brachyglottis greyi - NZ daisy bush2.png', 34, 1),
('Brachyglottis greyi - NZ daisy bush3.jpeg', 34, 1),
('Brachyglottis monroi - Monro_s daisy.jpg', 35, 1),
('Brachyglottis monroi - Monro_s daisy2.jpg', 35, 1),
('Brachyglottis monroi - Monro_s daisy3.jpg', 35, 1),
('Brachyglottis rotundifolia - muttonbird scrub.jpg', 36, 1),
('Brachyglottis rotundifolia - muttonbird scrub2.jpg', 36, 1),
('Brachyglottis rotundifolia - muttonbird scrub3.jpg', 36, 1),
('Brachyglottis rotundifolia - muttonbird scrub4.jpg', 36, 1),
('Buxus sempervirens - box hedge.jpg', 37, 1),
('Buxus sempervirens - box hedge2.jpeg', 37, 1),
('Buxus sempervirens - box hedge3.jpeg', 37, 1),
('Buxus sempervirens - box hedge4.jpeg', 37, 1),
('Buxus sempervirens - box hedge5.jpg', 37, 1),
('Callistemon sp. - bottle brush.jpeg', 38, 1),
('Callistemon sp. - bottle brush2.jpeg', 38, 1),
('Callistemon sp. - bottle brush3.jpeg', 38, 1),
('Callistemon sp. - bottle brush4.png', 38, 1),
('Camellia japonica - Japanese camelia.jpg', 39, 1),
('Camellia japonica - Japanese camelia2.jpg', 39, 1),
('Camellia japonica - Japanese camelia3.jpg', 39, 1),
('Camellia japonica - Japanese camelia4.jpeg', 39, 1),
('Camellia japonica - Japanese camelia5.jpg', 39, 1),
('Camellia japonica - Japanese camelia6.jpg', 39, 1),
('Camellia sasanqua - autumn camellia.jpeg', 40, 1),
('Camellia sasanqua - autumn camellia2.jpg', 40, 1),
('Camellia sasanqua - autumn camellia3.jpg', 40, 1),
('Camellia sasanqua - autumn camellia4.jpg', 40, 1),
('Camellia sasanqua - autumn camellia5.jpg', 40, 1),
('Camellia sasanqua - autumn camellia6.jpg', 40, 1),
('Canna X generalis - canna lily.jpg', 41, 1),
('Canna X generalis - canna lily2.jpg', 41, 1),
('Canna X generalis - canna lily3.jpg', 41, 1),
('Canna X generalis - canna lily4.jpg', 41, 1),
('Canna X generalis - canna lily5.jpg', 41, 1),
('Canna X generalis - canna lily6.jpg', 41, 1),
('Canna X generalis - canna lily7.jpg', 41, 1),
('Canna X generalis - canna lily8.jpg', 41, 1),
('Canna X generalis - canna lily9.jpg', 41, 1),
('Canna X generalis - canna lily10.jpg', 41, 1),
('Carex secta - pukio.jpg', 42, 1),
('Carex secta - pukio2.jpg', 42, 1),
('Carex secta - pukio3.jpg', 42, 1),
('Carex secta - pukio4.jpg', 42, 1),
('Carex testacea - orange sedge.jpg', 43, 1),
('Carex testacea - orange sedge2.jpg', 43, 1),
('Carmichaelia appressa - native prostrate broom.jpg', 44, 1),
('Carmichaelia appressa - native prostrate broom2.jpg', 44, 1),
('Carmichaelia appressa - native prostrate broom3.jpg', 44, 1),
('Carmichaelia appressa - native prostrate broom4.jpeg', 44, 1),
('Carmichaelia australis - NZ Native Broom.jpg', 45, 1),
('Carmichaelia australis - NZ Native Broom2.jpg', 45, 1),
('Carmichaelia australis - NZ Native Broom3.jpg', 45, 1),
('Carmichaelia australis - NZ Native Broom4.jpg', 45, 1),
('Carmichaelia stevensonii - weeping broom.jpg', 46, 1),
('Carmichaelia stevensonii - weeping broom2.jpg', 46, 1),
('Carmichaelia stevensonii - weeping broom3.jpeg', 46, 1),
('Carmichaelia stevensonii - weeping broom4.jpeg', 46, 1),
('Carmichaelia williamsii - NZ giant flowering broom.jpeg', 47, 1),
('Carmichaelia williamsii - NZ giant flowering broom2.jpeg', 47, 1),
('Carpinus betulus - European hornbeam.jpg', 48, 1),
('Carpinus betulus - European hornbeam2.jpg', 48, 1),
('Carpinus betulus - European hornbeam3.jpg', 48, 1),
('Carpinus betulus - European hornbeam4.jpeg', 48, 1),
('Carpinus betulus - European hornbeam5.jpeg', 48, 1),
('Carpodetus serratus - marble leaf or putaputaweta.jpg', 49, 1),
('Carpodetus serratus - marble leaf or putaputaweta2.jpg', 49, 1),
('Catalpa bignonioides - Indian bean tree.jpeg', 50, 1),
('Catalpa bignonioides - Indian bean tree2.jpg', 50, 1),
('Catalpa bignonioides - Indian bean tree3.jpg', 50, 1),
('Catalpa bignonioides - Indian bean tree4.jpg', 50, 1),
('Catalpa bignonioides - Indian bean tree5.jpg', 50, 1),
('Celmisia sp. - mountain daisy.jpeg', 51, 1),
('Celmisia sp. - mountain daisy2.jpg', 51, 1),
('Cercis canadensis _Texas White_ - Texas white redbud.jpg', 52, 1),
('Cercis canadensis _Texas White_ - Texas white redbud2.jpg', 52, 1),
('Cercis canadensis _Texas White_ - Texas white redbud3.jpg', 52, 1),
('Chamaecytisus palmensis - Tree Lucerne.jpeg', 53, 1),
('Chamaecytisus palmensis - Tree Lucerne2.jpeg', 53, 1),
('Chamaecytisus palmensis - Tree Lucerne3.jpeg', 53, 1),
('Chamaecytisus palmensis - Tree Lucerne4.jpeg', 53, 1),
('Chamaecytisus palmensis - Tree Lucerne5.jpeg', 53, 1),
('Chamaecytisus palmensis - Tree Lucerne6.jpeg', 53, 1),
('Chamaecytisus palmensis - Tree Lucerne7.jpg', 53, 1),
('Chimonanthus praecox - wintersweet.jpg', 54, 1),
('Chimonanthus praecox - wintersweet2.jpg', 54, 1),
('Chimonanthus praecox - wintersweet3.jpg', 54, 1),
('Chimonanthus praecox - wintersweet4.jpg', 54, 1),
('Chimonanthus praecox - wintersweet5.jpg', 54, 1),
('Chimonanthus praecox - wintersweet6.jpg', 54, 1),
('Chimonanthus praecox - wintersweet7.jpg', 54, 1),
('Chimonanthus praecox - wintersweet8.jpg', 54, 1),
('Chimonanthus praecox - wintersweet9.jpg', 54, 1),
('Chionochloa flavicans - miniature toetoe.jpg', 55, 1),
('Chionochloa flavicans - miniature toetoe2.jpg', 55, 1),
('Chionochloa rubra - Red Tussock.jpg', 56, 1),
('Chionochloa rubra - Red Tussock2.jpg', 56, 1),
('Chionochloa rubra - Red Tussock3.jpg', 56, 1),
('Choisya ternata - Mexican orange blossom.jpg', 57, 1),
('Choisya ternata - Mexican orange blossom2.jpg', 57, 1),
('Choisya ternata - Mexican orange blossom3.jpg', 57, 1),
('Choisya X dewitteana _Aztec Pearl_ - Mexican orange blossom.jpeg', 58, 1),
('Choisya X dewitteana _Aztec Pearl_ - Mexican orange blossom2.jpeg', 58, 1),
('Choisya X dewitteana _Aztec Pearl_ - Mexican orange blossom3.jpeg', 58, 1),
('Choisya X dewitteana _Aztec Pearl_ - Mexican orange blossom4.jpeg', 58, 1),
('Choisya X dewitteana _Aztec Pearl_ - Mexican orange blossom5.jpeg', 58, 1),
('Clematis afoliata - Leafless Clematis.jpg', 59, 1),
('Clematis afoliata - Leafless Clematis2.jpg', 59, 1),
('Clematis afoliata - Leafless Clematis3.jpg', 59, 1),
('Clematis paniculata - puawhananga.jpg', 60, 1),
('Clematis paniculata - puawhananga2.jpg', 60, 1),
('Clematis paniculata - puawhananga3.jpg', 60, 1),
('Clematis paniculata - puawhananga4.jpg', 60, 1),
('Clianthus maximus - kakabeak.jpg', 61, 1),
('Clianthus maximus - kakabeak2.jpg', 61, 1),
('Clianthus maximus - kakabeak3.jpg', 61, 1),
('Clianthus maximus - kakabeak4.jpeg', 61, 1),
('Clivia sp. - natal or bush lily.webp', 62, 1),
('Clivia sp. - natal or bush lily2.webp', 62, 1),
('Clivia sp. - natal or bush lily3.jpeg', 62, 1),
('Coleonema pulchrum _Sunset Gold_ - confetti bush.jpg', 63, 1),
('Coleonema pulchrum _Sunset Gold_ - confetti bush2.jpeg', 63, 1),
('Coleonema pulchrum _Sunset Gold_ - confetti bush3.jpg', 63, 1),
('Coleonema pulchrum _Sunset Gold_ - confetti bush4.jpg', 63, 1),
('Coleonema pulchrum _Sunset Gold_ - confetti bush5.jpg', 63, 1),
('Convolvulus cneorum - morning glory or silverbush.jpg', 64, 1),
('Convolvulus cneorum - morning glory or silverbush2.jpg', 64, 1),
('Convolvulus cneorum - morning glory or silverbush3.jpg', 64, 1),
('Convolvulus cneorum - morning glory or silverbush4.jpg', 64, 1),
('Convolvulus cneorum - morning glory or silverbush5.jpeg', 64, 1),
('Convolvulus cneorum - morning glory or silverbush6.jpg', 64, 1),
('Coprosma acerosa _Hawera_ - Hawera sand coprosma.jpeg', 65, 1),
('Coprosma acerosa _Hawera_ - Hawera sand coprosma2.jpeg', 65, 1),
('Coprosma acerosa _Hawera_ - Hawera sand coprosma3.jpg', 65, 1),
('Coprosma _Black Cloud_ - Black Cloud Coprosma.jpeg', 66, 1),
('Coprosma _Black Cloud_ - Black Cloud Coprosma2.jpg', 66, 1),
('Coprosma _Black Cloud_ - Black Cloud Coprosma3.jpg', 66, 1),
('Coprosma propinqua - mingimingi.jpeg', 67, 1),
('Coprosma propinqua - mingimingi2.jpeg', 67, 1),
('Coprosma propinqua - mingimingi3.jpg', 67, 1),
('Coprosma propinqua - mingimingi4.jpg', 67, 1),
('Coprosma propinqua - mingimingi5.jpeg', 67, 1),
('Coprosma repens - mIrror bush or taupata.jpg', 68, 1),
('Coprosma repens - mIrror bush or taupata2.jpeg', 68, 1),
('Coprosma repens - mIrror bush or taupata3.jpg', 68, 1),
('Coprosma repens - mIrror bush or taupata4.jpg', 68, 1),
('Coprosma repens - mIrror bush or taupata5.jpg', 68, 1),
('Coprosma repens - mIrror bush or taupata6.jpg', 68, 1),
('Coprosma repens - mIrror bush or taupata7.jpg', 68, 1),
('Coprosma repens - mIrror bush or taupata8.jpg', 68, 1),
('Coprosma repens - mIrror bush or taupata9.jpg', 68, 1),
('Coprosma rugosa _Lobster_ - red coprosma.jpg', 69, 1),
('Coprosma rugosa _Lobster_ - red coprosma2.jpg', 69, 1),
('Coprosma rugosa _Lobster_ - red coprosma3.jpg', 69, 1),
('Coprosma rugosa _Lobster_ - red coprosma4.jpg', 69, 1),
('Coprosma X kirkii - groundcover coprosma.jpg', 70, 1),
('Coprosma X kirkii - groundcover coprosma2.jpg', 70, 1),
('Coprosma X kirkii - groundcover coprosma3.jpg', 70, 1),
('Cordyline australis - cabbage tree.jpeg', 71, 1),
('Cordyline australis - cabbage tree2.jpg', 71, 1),
('Cordyline australis - cabbage tree3.jpeg', 71, 1),
('Cordyline australis - cabbage tree4.jpeg', 71, 1),
('Cordyline australis - cabbage tree5.jpg', 71, 1),
('Cornus alba - Siberian dogwood.jpg', 72, 1),
('Cornus alba - Siberian dogwood2.jpeg', 72, 1),
('Cornus alba - Siberian dogwood3.jpg', 72, 1),
('Cornus alba - Siberian dogwood4.jpg', 72, 1),
('Cornus alba - Siberian dogwood5.jpg', 72, 1),
('Cornus alba - Siberian dogwood6.jpg', 72, 1),
('Cornus alba - Siberian dogwood7.jpg', 72, 1),
('Cornus alba - Siberian dogwood8.jpg', 72, 1),
('Cornus alba - Siberian dogwood9.jpg', 72, 1),
('Cornus florida - dogwood.jpg', 73, 1),
('Cornus florida - dogwood2.jpg', 73, 1),
('Cornus florida - dogwood3.jpg', 73, 1),
('Cornus florida - dogwood4.jpg', 73, 1),
('Cornus florida - dogwood5.jpg', 73, 1),
('Cornus florida - dogwood6.jpg', 73, 1),
('Corokia X virgata _Bronze King_ - bronze corokia.jpg', 74, 1),
('Corokia X virgata _Bronze King_ - bronze corokia2.jpeg', 74, 1),
('Corokia X virgata _Bronze King_ - bronze corokia3.jpg', 74, 1),
('Corylus avellana - common hazel.jpeg', 75, 1),
('Corylus avellana - common hazel2.jpg', 75, 1),
('Corylus avellana - common hazel3.jpeg', 75, 1),
('Corylus avellana - common hazel4.jpg', 75, 1),
('Corylus avellana - common hazel5.jpeg', 75, 1),
('Corylus avellana - common hazel6.jpg', 75, 1),
('Corynocarpus laevigatus - karaka or NZ laurel.jpg', 76, 1),
('Corynocarpus laevigatus - karaka or NZ laurel2.jpg', 76, 1),
('Corynocarpus laevigatus - karaka or NZ laurel3.jpg', 76, 1),
('Corynocarpus laevigatus - karaka or NZ laurel4.jpg', 76, 1),
('Cotinus coggygria - smoke bush.jpg', 77, 1),
('Cotinus coggygria - smoke bush2.jpg', 77, 1),
('Cotinus coggygria - smoke bush3.jpg', 77, 1),
('Cotinus coggygria - smoke bush4.jpg', 77, 1),
('Cotoneaster horizontalis - rock spray.jpg', 78, 1),
('Cotoneaster horizontalis - rock spray2.jpg', 78, 1),
('Cotoneaster horizontalis - rock spray3.jpg', 78, 1),
('Cotoneaster horizontalis - rock spray4.jpg', 78, 1),
('Cotoneaster horizontalis - rock spray5.jpg', 78, 1),
('Cotoneaster horizontalis - rock spray6.jpg', 78, 1),
('Cotoneaster horizontalis - rock spray7.jpg', 78, 1),
('Cupressus macrocarpa - macrocarpa.jpg', 79, 1),
('Cupressus macrocarpa - macrocarpa2.jpg', 79, 1),
('Cupressus macrocarpa - macrocarpa3.jpg', 79, 1),
('Cupressus macrocarpa - macrocarpa4.jpg', 79, 1),
('Cupressus sempervirens - Italian cypress.jpg', 80, 1),
('Cupressus sempervirens - Italian cypress2.jpg', 80, 1),
('Cupressus sempervirens - Italian cypress3.jpg', 80, 1),
('Cupressus sempervirens - Italian cypress4.jpg', 80, 1),
('Cyclamen hederifolium - ivy leaved cyclamen.jpg', 81, 1),
('Cyclamen hederifolium - ivy leaved cyclamen2.jpg', 81, 1),
('Cyclamen hederifolium - ivy leaved cyclamen3.jpg', 81, 1),
('Cyclamen hederifolium - ivy leaved cyclamen4.jpg', 81, 1),
('Cytisus proliferus - tree lucerne or tagasaste.jpg', 82, 1),
('Cytisus proliferus - tree lucerne or tagasaste2.jpg', 82, 1),
('Cytisus proliferus - tree lucerne or tagasaste3.jpg', 82, 1),
('Cytisus proliferus - tree lucerne or tagasaste4.jpeg', 82, 1),
('Dacrydium cupressinum - rimu.jpg', 83, 1),
('Dacrydium cupressinum - rimu2.jpg', 83, 1),
('Dacrydium cupressinum - rimu3.jpg', 83, 1),
('Dacrydium cupressinum - rimu4.jpg', 83, 1),
('Daphne bholua - Nepalese paper plant.jpg', 84, 1),
('Daphne bholua - Nepalese paper plant2.jpg', 84, 1),
('Daphne bholua - Nepalese paper plant3.jpg', 84, 1),
('Daphne bholua - Nepalese paper plant4.jpg', 84, 1),
('Daphne bholua - Nepalese paper plant5.jpg', 84, 1),
('Daphne odora - winter daphne.jpg', 85, 1),
('Daphne odora - winter daphne2.jpeg', 85, 1),
('Daphne odora - winter daphne3.jpg', 85, 1),
('Daphne odora - winter daphne4.jpg', 85, 1),
('Daphne odora - winter daphne5.jpg', 85, 1),
('Daphne odora - winter daphne6.jpg', 85, 1),
('Daphne odora - winter daphne7.jpg', 85, 1),
('Daphne odora - winter daphne8.jpg', 85, 1),
('Dianella nigra - turutu.jpeg', 86, 1),
('Dianella nigra - turutu2.jpg', 86, 1),
('Dianella nigra - turutu3.jpg', 86, 1),
('Dianella nigra - turutu4.jpg', 86, 1),
('Dianella sp. _Little Rev_ - dianella.jpeg', 87, 1),
('Dianella sp. _Little Rev_ - dianella2.jpeg', 87, 1),
('Dianella sp. _Little Rev_ - dianella3.jpeg', 87, 1),
('Dianella tasmania _Blaze_ - Dianella.jpg', 88, 1),
('Dianella tasmania _Blaze_ - Dianella2.jpg', 88, 1),
('Dianella tasmania _Blaze_ - Dianella3.jpg', 88, 1),
('Dicksonia squarrosa - wheki or rough tree fern.jpg', 89, 1),
('Dicksonia squarrosa - wheki or rough tree fern2.jpg', 89, 1),
('Dicksonia squarrosa - wheki or rough tree fern3.jpg', 89, 1),
('Dicksonia squarrosa - wheki or rough tree fern4.jpg', 89, 1),
('Discaria toumatou - matagouri.jpg', 90, 1),
('Discaria toumatou - matagouri2.jpg', 90, 1),
('Discaria toumatou - matagouri3.jpg', 90, 1),
('Discaria toumatou - matagouri4.jpg', 90, 1),
('Disphyma australe - horokaka or native ice plant.jpg', 91, 1),
('Disphyma australe - horokaka or native ice plant2.jpg', 91, 1),
('Disphyma australe - horokaka or native ice plant3.jpg', 91, 1),
('Dodonaea viscosa _Purpurea_ - akeake or hopbush.jpg', 92, 1),
('Dodonaea viscosa _Purpurea_ - akeake or hopbush2.jpeg', 92, 1),
('Dodonaea viscosa _Purpurea_ - akeake or hopbush3.jpeg', 92, 1),
('Dodonaea viscosa _Purpurea_ - akeake or hopbush4.jpeg', 92, 1),
('Dracophyllum sinclairii - inaka or neinei.jpg', 93, 1),
('Dracophyllum sinclairii - inaka or neinei2.jpg', 93, 1),
('Dracophyllum sinclairii - inaka or neinei3.jpg', 93, 1),
('Echium candicans - pride of Madeira.jpg', 94, 1),
('Echium candicans - pride of Madeira2.jpg', 94, 1),
('Echium candicans - pride of Madeira3.jpg', 94, 1),
('Echium candicans - pride of Madeira4.jpeg', 94, 1),
('Echium candicans - pride of Madeira5.jpg', 94, 1),
('Eucalyptus viminalis - manna gum.jpg', 95, 1),
('Eucalyptus viminalis - manna gum2.jpg', 95, 1),
('Eucalyptus viminalis - manna gum3.jpg', 95, 1),
('Eucalyptus viminalis - manna gum4.jpg', 95, 1),
('Eucalyptus viminalis - manna gum5.jpg', 95, 1),
('Euphorbia glauca - shore spurge or waiu-atua.jpg', 96, 1),
('Euphorbia glauca - shore spurge or waiu-atua2.jpg', 96, 1),
('Euphorbia glauca - shore spurge or waiu-atua3.jpg', 96, 1),
('Euphorbia glauca - shore spurge or waiu-atua4.jpg', 96, 1),
('Euphorbia glauca - shore spurge or waiu-atua5.jpg', 96, 1),
('Euphorbia glauca - shore spurge or waiu-atua6.jpg', 96, 1),
('Euphorbia glauca - shore spurge or waiu-atua7.jpg', 96, 1),
('Euphorbia glauca - shore spurge or waiu-atua8.jpg', 96, 1),
('Euphorbia glauca - shore spurge or waiu-atua9.jpg', 96, 1),
('Fagus sylvatica - common or English beech.jpg', 97, 1),
('Fagus sylvatica - common or English beech2.jpg', 97, 1),
('Fagus sylvatica - common or English beech3.jpeg', 97, 1),
('Fagus sylvatica - common or English beech4.jpg', 97, 1),
('Fagus sylvatica - common or English beech5.jpg', 97, 1),
('Fagus sylvatica - common or English beech6.jpg', 97, 1),
('Fagus sylvatica - common or English beech7.jpg', 97, 1),
('Fatsia japonica - Japanese Aralia.jpg', 98, 1),
('Fatsia japonica - Japanese Aralia2.jpg', 98, 1),
('Fatsia japonica - Japanese Aralia3.jpg', 98, 1),
('Festuca actae - Banks Peninsula blue tussock.jpg', 99, 1),
('Festuca actae - Banks Peninsula blue tussock2.jpeg', 99, 1),
('Ficus pumila - creeping fig.jpg', 100, 1),
('Ficus pumila - creeping fig2.jpg', 100, 1),
('Ficus pumila - creeping fig3.jpg', 100, 1),
('Ficus pumila - creeping fig4.jpg', 100, 1),
('Fraxinus excelsior - European or common ash.jpg', 101, 1),
('Fraxinus excelsior - European or common ash2.jpg', 101, 1),
('Fraxinus excelsior - European or common ash3.jpg', 101, 1),
('Fraxinus excelsior - European or common ash4.jpg', 101, 1),
('Fraxinus excelsior - European or common ash5.jpeg', 101, 1),
('Fraxinus excelsior - European or common ash6.jpg', 101, 1),
('Fuchsia procumbens - creeping fuchsia.jpg', 102, 1),
('Fuchsia procumbens - creeping fuchsia2.jpg', 102, 1),
('Fuchsia procumbens - creeping fuchsia3.jpg', 102, 1),
('Fuchsia procumbens - creeping fuchsia4.jpg', 102, 1),
('Fuchsia procumbens - creeping fuchsia5.jpg', 102, 1),
('Fuscospora cliffortioides - mountain beech.jpeg', 103, 1),
('Fuscospora cliffortioides - mountain beech2.jpeg', 103, 1),
('Fuscospora cliffortioides - mountain beech3.jpg', 103, 1),
('Fuscospora cliffortioides - mountain beech4.jpg', 103, 1),
('Fuscospora cliffortioides - mountain beech5.jpg', 103, 1),
('Fuscospora cliffortioides - mountain beech6.jpeg', 103, 1),
('Fuscospora cliffortioides - mountain beech7.jpeg', 103, 1),
('Fuscospora fusca - red beech.jpg', 104, 1),
('Fuscospora fusca - red beech2.jpg', 104, 1),
('Fuscospora fusca - red beech3.jpeg', 104, 1),
('Fuscospora fusca - red beech4.jpeg', 104, 1),
('Fuscospora fusca - red beech5.jpeg', 104, 1),
('Fuscospora fusca - red beech6.jpg', 104, 1),
('Fuscospora solandri - black beech.jpg', 105, 1),
('Fuscospora solandri - black beech2.jpg', 105, 1),
('Fuscospora solandri - black beech3.jpg', 105, 1),
('Fuscospora solandri - black beech4.jpg', 105, 1),
('Fuscospora solandri - black beech5.jpg', 105, 1),
('Fuscospora solandri - black beech6.jpg', 105, 1),
('Garrya elliptica - Silk Tassel Bush.jpg', 106, 1),
('Garrya elliptica - Silk Tassel Bush2.jpg', 106, 1),
('Garrya elliptica - Silk Tassel Bush3.jpg', 106, 1),
('Garrya elliptica - Silk Tassel Bush4.jpg', 106, 1),
('Garrya elliptica - Silk Tassel Bush5.jpg', 106, 1),
('Garrya elliptica - Silk Tassel Bush6.jpg', 106, 1),
('Garrya elliptica - Silk Tassel Bush7.jpg', 106, 1),
('Garrya elliptica - Silk Tassel Bush8.jpg', 106, 1),
('Ginkgo biloba - maidenhair tree.jpg', 107, 1),
('Ginkgo biloba - maidenhair tree2.jpg', 107, 1),
('Grevillea banksii X bipinnatifida - grevillea.jpg', 108, 1),
('Grevillea banksii X bipinnatifida - grevillea2.jpg', 108, 1),
('Grevillea banksii X bipinnatifida - grevillea3.jpg', 108, 1),
('Griselinia littoralis - broadleaf or kapuka.jpg', 109, 1),
('Griselinia littoralis - broadleaf or kapuka2.jpg', 109, 1),
('Griselinia littoralis - broadleaf or kapuka3.jpg', 109, 1),
('Griselinia littoralis - broadleaf or kapuka4.jpg', 109, 1),
('Haloregis erecta _Purpurea_ - toatoa.jpg', 110, 1),
('Haloregis erecta _Purpurea_ - toatoa2.jpg', 110, 1),
('Haloregis erecta _Purpurea_ - toatoa3.jpg', 110, 1),
('Hamamelis mollis - witch hazel.jpg', 111, 1),
('Hamamelis mollis - witch hazel2.jpg', 111, 1),
('Hamamelis mollis - witch hazel3.jpg', 111, 1),
('Hamamelis mollis - witch hazel4.jpeg', 111, 1),
('Hamamelis mollis - witch hazel5.jpeg', 111, 1),
('Hamamelis mollis - witch hazel6.jpg', 111, 1),
('Hamamelis mollis - witch hazel7.jpg', 111, 1),
('Heliohebe hulkeana - New Zealand lilac.jpg', 112, 1),
('Heliohebe hulkeana - New Zealand lilac2.jpg', 112, 1),
('Heliohebe hulkeana - New Zealand lilac3.jpg', 112, 1),
('Heliohebe hulkeana - New Zealand lilac4.jpg', 112, 1),
('Helleborus argutifolius - Corsican hellebore.jpg', 113, 1),
('Helleborus argutifolius - Corsican hellebore2.jpg', 113, 1),
('Helleborus argutifolius - Corsican hellebore3.jpg', 113, 1),
('Helleborus argutifolius - Corsican hellebore4.jpeg', 113, 1),
('Helleborus argutifolius - Corsican hellebore5.jpg', 113, 1),
('Helleborus foetidus - Stinking Hellebore.jpg', 114, 1),
('Helleborus foetidus - Stinking Hellebore2.jpg', 114, 1),
('Helleborus foetidus - Stinking Hellebore3.jpeg', 114, 1),
('Helleborus foetidus - Stinking Hellebore4.jpg', 114, 1),
('Helleborus foetidus - Stinking Hellebore5.jpeg', 114, 1),
('Helleborus orientalis - lenten rose.jpeg', 115, 1),
('Helleborus orientalis - lenten rose2.jpeg', 115, 1),
('Helleborus orientalis - lenten rose3.jpg', 115, 1),
('Helleborus orientalis - lenten rose4.jpg', 115, 1),
('Helleborus orientalis - lenten rose5.jpeg', 115, 1),
('Helleborus orientalis - lenten rose6.jpg', 115, 1),
('Hoheria angustifolia - narrow leaved lacebark.jpg', 116, 1),
('Hoheria angustifolia - narrow leaved lacebark2.jpg', 116, 1),
('Hoheria angustifolia - narrow leaved lacebark3.jpeg', 116, 1),
('Hoheria angustifolia - narrow leaved lacebark4.jpeg', 116, 1),
('Hoheria angustifolia - narrow leaved lacebark5.jpg', 116, 1),
('Hoheria lyallii - mountain lacebark.jpg', 117, 1),
('Hoheria lyallii - mountain lacebark2.jpg', 117, 1),
('Hoheria lyallii - mountain lacebark3.jpg', 117, 1),
('Hoheria sexstylosa - lacebark or houhere.jpeg', 118, 1),
('Hoheria sexstylosa - lacebark or houhere2.jpeg', 118, 1),
('Hoheria sexstylosa - lacebark or houhere3.jpeg', 118, 1),
('Hoheria sexstylosa - lacebark or houhere4.jpeg', 118, 1),
('Hoheria sexstylosa - lacebark or houhere5.jpeg', 118, 1),
('Hoheria sexstylosa - lacebark or houhere6.jpeg', 118, 1),
('Hydrangea macrophylla - mophead hydrangea.jpg', 119, 1),
('Hydrangea macrophylla - mophead hydrangea2.jpg', 119, 1),
('Hydrangea macrophylla - mophead hydrangea3.jpg', 119, 1),
('Hydrangea macrophylla - mophead hydrangea4.jpg', 119, 1),
('Hydrangea macrophylla - mophead hydrangea5.jpg', 119, 1),
('Hydrangea macrophylla - mophead hydrangea6.jpeg', 119, 1),
('Hydrangea macrophylla - mophead hydrangea7.jpeg', 119, 1),
('Hydrangea macrophylla - mophead hydrangea8.jpeg', 119, 1),
('Hydrangea macrophylla - mophead hydrangea9.jpg', 119, 1),
('Hydrangea macrophylla - mophead hydrangea10.jpeg', 119, 1),
('Hydrangea paniculata - panicled hydrangea.jpg', 120, 1),
('Hydrangea paniculata - panicled hydrangea2.jpeg', 120, 1),
('Hydrangea paniculata - panicled hydrangea3.jpg', 120, 1),
('Hydrangea paniculata - panicled hydrangea4.jpeg', 120, 1),
('Hydrangea paniculata - panicled hydrangea5.jpg', 120, 1),
('Hydrangea paniculata - panicled hydrangea6.jpg', 120, 1),
('Hydrangea paniculata - panicled hydrangea7.jpg', 120, 1),
('Hydrangea paniculata - panicled hydrangea8.jpg', 120, 1),
('Hydrangea paniculata - panicled hydrangea9.jpg', 120, 1),
('Hydrangea paniculata - panicled hydrangea10.jpeg', 120, 1),
('Hydrangea quercifolia _Pee Wee_ - oak leaf hydrangea.jpeg', 121, 1),
('Hydrangea quercifolia _Pee Wee_ - oak leaf hydrangea2.jpeg', 121, 1),
('Hydrangea quercifolia _Pee Wee_ - oak leaf hydrangea3.png', 121, 1),
('Ilex aquifolium - English holly.jpg', 122, 1),
('Ilex aquifolium - English holly2.jpg', 122, 1),
('Ilex aquifolium - English holly3.jpg', 122, 1),
('Ilex aquifolium - English holly4.jpg', 122, 1),
('Ilex aquifolium - English holly5.jpg', 122, 1),
('Ilex aquifolium - English holly6.jpg', 122, 1),
('Juncus pallidus - giant club rush.jpg', 123, 1),
('Juncus pallidus - giant club rush2.jpg', 123, 1),
('Juncus pallidus - giant club rush3.jpg', 123, 1),
('Juncus pallidus - giant club rush4.jpg', 123, 1),
('Knightia excelsa - rewarewa (NZ honeysuckle).jpg', 124, 1),
('Knightia excelsa - rewarewa (NZ honeysuckle)2.jpeg', 124, 1),
('Kunzea ericoides - kanuka.jpg', 125, 1),
('Kunzea ericoides - kanuka2.jpg', 125, 1),
('Kunzea ericoides - kanuka3.jpg', 125, 1),
('Kunzea ericoides - kanuka4.jpg', 125, 1),
('Kunzea ericoides - kanuka5.jpg', 125, 1),
('Laurus nobilis - bay tree.jpg', 126, 1),
('Laurus nobilis - bay tree2.jpg', 126, 1),
('Laurus nobilis - bay tree3.jpg', 126, 1),
('Laurus nobilis - bay tree4.jpg', 126, 1),
('Laurus nobilis - bay tree5.jpg', 126, 1),
('Lavandula X intermedia - hybrid lavender.jpeg', 127, 1),
('Lavandula X intermedia - hybrid lavender2.jpg', 127, 1),
('Lavandula X intermedia - hybrid lavender3.jpg', 127, 1),
('Lavandula X intermedia - hybrid lavender4.jpg', 127, 1),
('Lavandula X intermedia - hybrid lavender5.jpg', 127, 1),
('Leonohebe cupressoides - frangrant hebe.jpeg', 128, 1),
('Leonohebe cupressoides - frangrant hebe2.jpeg', 128, 1),
('Leonohebe cupressoides - frangrant hebe3.jpeg', 128, 1),
('Leucadendron argenteum - Silver Tree.jpg', 129, 1),
('Leucadendron argenteum - Silver Tree2.jpg', 129, 1),
('Leucadendron argenteum - Silver Tree3.jpg', 129, 1),
('Leucadendron argenteum - Silver Tree4.jpg', 129, 1),
('Leucadendron argenteum - Silver Tree5.jpg', 129, 1),
('Leucadendron salignum - conebush.jpg', 130, 1),
('Leucadendron salignum - conebush2.jpg', 130, 1),
('Leucadendron salignum - conebush3.jpg', 130, 1),
('Leucadendron salignum - conebush4.jpg', 130, 1),
("Libertia ixioides - NZ iris or mikoikoi.jpg", 131, 1),
('Libertia peregrinans - NZ iris.jpg', 132, 1),
('Libertia peregrinans - NZ iris2.jpg', 132, 1),
('Libertia peregrinans - NZ iris3.jpg', 132, 1),
('Liquidambar styraciflua - American sweetgum.jpg', 133, 1),
('Liquidambar styraciflua - American sweetgum2.jpg', 133, 1),
('Liquidambar styraciflua - American sweetgum3.jpg', 133, 1),
('Liquidambar styraciflua - American sweetgum4.jpg', 133, 1),
('Liquidambar styraciflua - American sweetgum5.jpg', 133, 1),
('Liriodendron tulipifera - tulip tree.jpg', 134, 1),
('Liriodendron tulipifera - tulip tree2.jpg', 134, 1),
('Liriodendron tulipifera - tulip tree3.jpg', 134, 1),
('Liriodendron tulipifera - tulip tree4.jpg', 134, 1),
('Liriodendron tulipifera - tulip tree5.jpg', 134, 1),
('Liriodendron tulipifera - tulip tree6.jpg', 134, 1),
('Lomandra longifolia - basket grass.jpeg', 135, 1),
('Lomandra longifolia - basket grass2.jpeg', 135, 1),
('Lomandra longifolia - basket grass3.jpeg', 135, 1),
('Lomaria discolor - crown fern.jpeg', 136, 1),
('Lomaria discolor - crown fern2.jpg', 136, 1),
('Lomaria discolor - crown fern3.jpg', 136, 1),
('Lomaria discolor - crown fern4.jpeg', 136, 1),
('Lophomyrtus obcordata - rohutu or NZ myrtle.jpg', 137, 1),
('Lophomyrtus obcordata - rohutu or NZ myrtle2.jpg', 137, 1),
('Lophomyrtus obcordata - rohutu or NZ myrtle3.jpg', 137, 1),
('Lophomyrtus obcordata - rohutu or NZ myrtle4.jpg', 137, 1),
('Lophomyrtus x ralphii - hybrid lophomyrtus or NZ myrtle.jpg', 138, 1),
('Lophomyrtus x ralphii - hybrid lophomyrtus or NZ myrtle2.jpg', 138, 1),
('Lophomyrtus x ralphii - hybrid lophomyrtus or NZ myrtle3.jpg', 138, 1),
('Lophozonia menziesii - silver beech.jpg', 139, 1),
('Lophozonia menziesii - silver beech2.jpg', 139, 1),
('Lophozonia menziesii - silver beech3.jpeg', 139, 1),
('Lophozonia menziesii - silver beech4.jpg', 139, 1),
('Lophozonia menziesii - silver beech5.jpeg', 139, 1),
('Magnolia grandiflora _Little Gem_ - dwarf magnolia.jpg', 140, 1),
('Magnolia grandiflora _Little Gem_ - dwarf magnolia2.jpg', 140, 1),
('Magnolia grandiflora _Little Gem_ - dwarf magnolia3.jpg', 140, 1),
('Magnolia grandiflora _Little Gem_ - dwarf magnolia4.jpg', 140, 1),
('Magnolia grandiflora _Little Gem_ - dwarf magnolia5.jpg', 140, 1),
('Magnolia grandiflora _Little Gem_ - dwarf magnolia6.jpg', 140, 1),
('Magnolia grandiflora _Little Gem_ - dwarf magnolia7.jpg', 140, 1),
('Magnolia grandiflora _Little Gem_ - dwarf magnolia8.jpg', 140, 1),
('Magnolia grandiflora _Little Gem_ - dwarf magnolia9.jpg', 140, 1),
('Magnolia liliflora _Nigra_ - deciduous magnolia.jpg', 141, 1),
('Magnolia liliflora _Nigra_ - deciduous magnolia2.jpg', 141, 1),
('Magnolia liliflora _Nigra_ - deciduous magnolia3.jpg', 141, 1),
('Magnolia liliflora _Nigra_ - deciduous magnolia4.jpg', 141, 1),
('Magnolia liliflora _Nigra_ - deciduous magnolia5.jpg', 141, 1),
('Magnolia liliflora _Nigra_ - deciduous magnolia6.jpg', 141, 1),
('Magnolia liliflora _Nigra_ - deciduous magnolia7.jpg', 141, 1),
('Magnolia X soulangeana - saucer or Chinese magnolia.jpg', 142, 1),
('Magnolia X soulangeana - saucer or Chinese magnolia2.jpg', 142, 1),
('Magnolia X soulangeana - saucer or Chinese magnolia3.jpg', 142, 1),
('Magnolia X soulangeana - saucer or Chinese magnolia4.jpg', 142, 1),
('Magnolia X soulangeana - saucer or Chinese magnolia5.jpeg', 142, 1),
('Magnolia X soulangeana - saucer or Chinese magnolia6.jpeg', 142, 1),
('Magnolia X soulangeana - saucer or Chinese magnolia7.jpg', 142, 1),
('Magnolia X soulangeana - saucer or Chinese magnolia8.jpeg', 142, 1),
('Magnolia X soulangeana - saucer or Chinese magnolia9.jpg', 142, 1),
('Magnolia X soulangeana - saucer or Chinese magnolia10.jpeg', 142, 1),
('Malus sp. - apple tree.jpg', 143, 1),
('Malus sp. - apple tree2.jpg', 143, 1),
('Malus sp. - apple tree3.jpg', 143, 1),
('Malus sp. - apple tree4.jpg', 143, 1),
('Malus sp. - apple tree5.jpg', 143, 1),
('Malus sp. - apple tree6.jpg', 143, 1),
('Melicytus alpinus - porcupine scrub.jpg', 144, 1),
('Melicytus alpinus - porcupine scrub2.jpg', 144, 1),
('Melicytus alpinus - porcupine scrub3.jpg', 144, 1),
('Melicytus alpinus - porcupine scrub4.jpeg', 144, 1),
('Melicytus lanceolatus - Narrow Leaved Mahoe.jpeg', 145, 1),
('Melicytus lanceolatus - Narrow Leaved Mahoe2.jpg', 145, 1),
('Melicytus lanceolatus - Narrow Leaved Mahoe3.jpeg', 145, 1),
('Melicytus ramiflorus - mahoe or whiteywood.jpg', 146, 1),
('Melicytus ramiflorus - mahoe or whiteywood2.jpg', 146, 1),
('Melicytus ramiflorus - mahoe or whiteywood3.jpg', 146, 1),
('Melicytus ramiflorus - mahoe or whiteywood4.jpg', 146, 1),
('Melicytus ramiflorus - mahoe or whiteywood5.jpg', 146, 1),
('Melicytus ramiflorus - mahoe or whiteywood6.jpg', 146, 1),
('Metrosideros umbellata - Southern Rata.jpg', 147, 1),
('Metrosideros umbellata - Southern Rata2.jpg', 147, 1),
('Metrosideros umbellata - Southern Rata3.jpg', 147, 1),
('Metrosideros umbellata - Southern Rata4.jpg', 147, 1),
('Metrosideros umbellata - Southern Rata5.jpg', 147, 1),
('Michelia yunnanensis - evergreen michelia.jpg', 148, 1),
('Michelia yunnanensis - evergreen michelia2.jpg', 148, 1),
('Microleana avenacea - bush rice grass.jpg', 149, 1),
('Microleana avenacea - bush rice grass2.jpg', 149, 1),
('Muehlenbeckia astonii - shrubby tororaro.jpg', 150, 1),
('Muehlenbeckia astonii - shrubby tororaro2.jpg', 150, 1),
('Muehlenbeckia astonii - shrubby tororaro3.jpg', 150, 1),
('Muehlenbeckia australis - pohuehue.jpg', 151, 1),
('Muehlenbeckia australis - pohuehue2.jpg', 151, 1),
('Muehlenbeckia australis - pohuehue3.jpg', 151, 1),
('Muehlenbeckia australis - pohuehue4.jpg', 151, 1),
('Muehlenbeckia australis - pohuehue5.jpg', 151, 1),
('Muehlenbeckia axillaris - creeping muehlenbeckia.jpg', 152, 1),
('Muehlenbeckia axillaris - creeping muehlenbeckia2.jpg', 152, 1),
('Muehlenbeckia axillaris - creeping muehlenbeckia3.jpg', 152, 1),
('Muehlenbeckia axillaris - creeping muehlenbeckia4.jpg', 152, 1),
('Muehlenbeckia axillaris - creeping muehlenbeckia5.jpg', 152, 1),
('Muehlenbeckia axillaris - creeping muehlenbeckia6.jpg', 152, 1),
('Muehlenbeckia axillaris - creeping muehlenbeckia7.jpg', 152, 1),
('Muehlenbeckia complexa - small-leaved pohuehue.jpg', 153, 1),
('Muehlenbeckia complexa - small-leaved pohuehue2.jpg', 153, 1),
('Muehlenbeckia complexa - small-leaved pohuehue3.jpg', 153, 1),
('Myoporum laetum - ngaio.jpg', 154, 1),
('Myoporum laetum - ngaio2.jpg', 154, 1),
('Myoporum laetum - ngaio3.jpg', 154, 1),
('Myoporum laetum - ngaio4.jpg', 154, 1),
('Myoporum laetum - ngaio5.jpg', 154, 1),
('Myosotidium hortensia - Chatham Island forget me not.jpeg', 155, 1),
('Myosotidium hortensia - Chatham Island forget me not2.jpeg', 155, 1),
('Myosotidium hortensia - Chatham Island forget me not3.jpeg', 155, 1),
('Nandina domestica ‘Pygmaea’ - dwarf heavenly bamboo.jpg', 156, 1),
('Nandina domestica ‘Pygmaea’ - dwarf heavenly bamboo2.jpg', 156, 1),
('Nandina domestica ‘Pygmaea’ - dwarf heavenly bamboo3.jpg', 156, 1),
('Nandina domestica ‘Pygmaea’ - dwarf heavenly bamboo4.jpg', 156, 1),
('Nandina domestica ‘Pygmaea’ - dwarf heavenly bamboo5.jpg', 156, 1),
('Narcissus sp. - Daffodil.jpeg', 157, 1),
('Narcissus sp. - Daffodil2.jpg', 157, 1),
('Narcissus sp. - Daffodil3.jpg', 157, 1),
('Narcissus sp. - Daffodil4.jpg', 157, 1),
('Narcissus sp. - Daffodil5.jpg', 157, 1),
('Narcissus sp. - Daffodil6.jpg', 157, 1),
('Nepeta mussinii - cat mint.jpg', 158, 1),
('Nepeta mussinii - cat mint2.jpg', 158, 1),
('Nepeta mussinii - cat mint3.jpeg', 158, 1),
('Nepeta mussinii - cat mint4.jpg', 158, 1),
('Nepeta mussinii - cat mint5.jpeg', 158, 1),
('Olea europaea - olive tree.jpeg', 159, 1),
('Olea europaea - olive tree2.jpg', 159, 1),
('Olea europaea - olive tree3.jpeg', 159, 1),
('Olea europaea - olive tree4.jpg', 159, 1),
('Olea europaea - olive tree5.jpeg', 159, 1),
('Olea europaea - olive tree6.jpg', 159, 1),
('Olearia cheesemanii - NZ daisy bush.jpg', 160, 1),
('Olearia cheesemanii - NZ daisy bush2.jpg', 160, 1),
('Olearia cheesemanii - NZ daisy bush3.jpg', 160, 1),
('Olearia lineata - twiggy tree daisy.jpg', 161, 1),
('Olearia lineata - twiggy tree daisy2.jpg', 161, 1),
('Olearia lineata - twiggy tree daisy3.jpg', 161, 1),
('Olearia lineata - twiggy tree daisy4.jpg', 161, 1),
('Olearia lineata - twiggy tree daisy5.jpg', 161, 1),
('Olearia paniculata - Golden Akeake or Akiraho.jpg', 162, 1),
('Olearia paniculata - Golden Akeake or Akiraho2.jpg', 162, 1),
('Olearia paniculata - Golden Akeake or Akiraho3.jpeg', 162, 1),
('Olearia paniculata - Golden Akeake or Akiraho4.jpeg', 162, 1),
('Olearia paniculata - Golden Akeake or Akiraho5.jpeg', 162, 1),
('Olearia paniculata - Golden Akeake or Akiraho6.jpg', 162, 1),
('Olearia X macrodonta - NZ or Mountain Holly.jpg', 163, 1),
('Olearia X macrodonta - NZ or Mountain Holly2.jpeg', 163, 1),
('Olearia X macrodonta - NZ or Mountain Holly3.jpeg', 163, 1),
('Olearia X macrodonta - NZ or Mountain Holly4.jpeg', 163, 1),
('Olearia X macrodonta - NZ or Mountain Holly5.jpeg', 163, 1),
('Ophiopogon planiscapus _Black Dragon_ - black mondo grass.jpg', 164, 1),
('Ophiopogon planiscapus _Black Dragon_ - black mondo grass2.jpg', 164, 1),
('Ophiopogon planiscapus _Black Dragon_ - black mondo grass3.jpg', 164, 1),
('Ophiopogon planiscapus _Black Dragon_ - black mondo grass4.jpg', 164, 1),
('Ophiopogon planiscapus _Black Dragon_ - black mondo grass5.jpg', 164, 1),
('Ozothamnus leptophylllus - Cottonwood or Tauhinu.jpg', 165, 1),
('Ozothamnus leptophylllus - Cottonwood or Tauhinu2.jpg', 165, 1),
('Ozothamnus leptophylllus - Cottonwood or Tauhinu3.jpg', 165, 1),
('Ozothamnus leptophylllus - Cottonwood or Tauhinu4.jpg', 165, 1),
('Ozothamnus leptophylllus - Cottonwood or Tauhinu5.jpg', 165, 1),
('Ozothamnus leptophylllus - Cottonwood or Tauhinu6.jpg', 165, 1),
('Ozothamnus leptophylllus - Cottonwood or Tauhinu7.jpg', 165, 1),
('Ozothamnus leptophylllus - Cottonwood or Tauhinu8.jpg', 165, 1),
('Ozothamnus leptophylllus - Cottonwood or Tauhinu9.jpg', 165, 1),
('Ozothamnus leptophylllus - Cottonwood or Tauhinu10.jpg', 165, 1),
('Pachysandra terminalis - Japanese spurge.jpg', 166, 1),
('Pachysandra terminalis - Japanese spurge2.jpg', 166, 1),
('Pachysandra terminalis - Japanese spurge3.jpeg', 166, 1),
('Pachysandra terminalis - Japanese spurge4.jpg', 166, 1),
('Pachysandra terminalis - Japanese spurge5.jpg', 166, 1),
('Pachysandra terminalis - Japanese spurge6.jpg', 166, 1),
('Pachysandra terminalis - Japanese spurge7.jpg', 166, 1),
('Pachystegia insignis - Malborough rock daisy.jpeg', 167, 1),
('Pachystegia insignis - Malborough rock daisy2.jpeg', 167, 1),
('Pachystegia insignis - Malborough rock daisy3.jpeg', 167, 1),
('Pachystegia insignis - Malborough rock daisy4.jpg', 167, 1),
('Pachystegia insignis - Malborough rock daisy5.jpeg', 167, 1),
('Pachystegia insignis - Malborough rock daisy6.jpeg', 167, 1),
('Pachystegia insignis - Malborough rock daisy7.jpeg', 167, 1),
('Pachystegia insignis - Malborough rock daisy8.jpeg', 167, 1),
('Pachystegia insignis - Malborough rock daisy9.jpg', 167, 1),
('Pachystegia insignis - Malborough rock daisy10.jpeg', 167, 1),
('Pachystegia rufa - Marlborough rock daisy.jpg', 168, 1),
('Pachystegia rufa - Marlborough rock daisy2.jpg', 168, 1),
('Pachystegia rufa - Marlborough rock daisy3.jpg', 168, 1),
('Pachystegia rufa - Marlborough rock daisy4.jpg', 168, 1),
('Pectinopitys ferruginea - miro.jpg', 169, 1),
('Pectinopitys ferruginea - miro2.jpg', 169, 1),
('Pectinopitys ferruginea - miro3.jpg', 169, 1),
('Pectinopitys ferruginea - miro4.jpg', 169, 1),
('Pectinopitys ferruginea - miro5.jpg', 169, 1),
('Phebalium squameum - satinwood.jpg', 170, 1),
('Phebalium squameum - satinwood2.jpg', 170, 1),
('Phebalium squameum - satinwood3.jpg', 170, 1),
('Phebalium squameum - satinwood4.jpg', 170, 1),
('Phebalium squameum - satinwood5.jpg', 170, 1),
('Phormium cookianum - wharariki or mountain Flax.jpg', 171, 1),
('Phormium cookianum - wharariki or mountain Flax2.jpg', 171, 1),
('Phormium cookianum - wharariki or mountain Flax3.jpg', 171, 1),
('Phormium cookianum - wharariki or mountain Flax4.jpg', 171, 1),
('Phormium cookianum - wharariki or mountain Flax5.jpg', 171, 1),
('Phormium cookianum - wharariki or mountain Flax6.jpg', 171, 1),
('Phormium cookianum - wharariki or mountain Flax7.jpg', 171, 1),
('Phormium tenax - harakeke or NZ flax.jpg', 172, 1),
('Phormium tenax - harakeke or NZ flax2.jpg', 172, 1),
('Phormium tenax - harakeke or NZ flax3.jpg', 172, 1),
('Phormium tenax - harakeke or NZ flax4.jpg', 172, 1),
('Phormium tenax - harakeke or NZ flax5.jpg', 172, 1),
('Phormium tenax - harakeke or NZ flax6.jpg', 172, 1),
('Photinia X fraseri _Robusta_ - photinia.jpg', 173, 1),
('Photinia X fraseri _Robusta_ - photinia2.jpeg', 173, 1),
('Photinia X fraseri _Robusta_ - photinia3.jpg', 173, 1),
('Photinia X fraseri _Robusta_ - photinia4.jpg', 173, 1),
('Photinia X fraseri _Robusta_ - photinia5.jpg', 173, 1),
('Photinia X fraseri _Robusta_ - photinia6.jpg', 173, 1),
('Phyllocladus alpinus - mountain toatoa or celery pine.jpg', 174, 1),
('Phyllocladus alpinus - mountain toatoa or celery pine2.jpg', 174, 1),
('Phyllocladus alpinus - mountain toatoa or celery pine3.jpg', 174, 1),
('Phyllocladus trichomanoides - tenakaha.jpg', 175, 1),
('Phyllocladus trichomanoides - tenakaha2.jpg', 175, 1),
('Phyllocladus trichomanoides - tenakaha3.png', 175, 1),
('Pieris japonica - lily of the valley.jpg', 176, 1),
('Pieris japonica - lily of the valley2.jpg', 176, 1),
('Pieris japonica - lily of the valley3.jpg', 176, 1),
('Pieris japonica - lily of the valley4.jpg', 176, 1),
('Pieris japonica - lily of the valley5.jpg', 176, 1),
('Pieris japonica - lily of the valley6.jpg', 176, 1),
('Pieris japonica - lily of the valley7.jpg', 176, 1),
('Pieris japonica - lily of the valley8.jpg', 176, 1),
('Pieris japonica - lily of the valley9.jpeg', 176, 1),
('Pieris japonica - lily of the valley10.jpg', 176, 1),
('Pimelea prostrata - NZ daphne.jpg', 177, 1),
('Pimelea prostrata - NZ daphne2.jpg', 177, 1),
('Pimelea prostrata - NZ daphne3.jpg', 177, 1),
('Pimelea prostrata - NZ daphne4.jpg', 177, 1),
('Pimelea prostrata - NZ daphne5.jpeg', 177, 1),
('Pimelea prostrata - NZ daphne6.jpeg', 177, 1),
('Pimelea prostrata - NZ daphne7.jpeg', 177, 1),
('Pimelea prostrata - NZ daphne8.jpg', 177, 1),
('Pimelea prostrata - NZ daphne9.jpg', 177, 1),
('Piper excelsum - kawakawa.jpg', 178, 1),
('Piper excelsum - kawakawa2.jpg', 178, 1),
('Piper excelsum - kawakawa3.jpg', 178, 1),
('Piper excelsum - kawakawa4.jpg', 178, 1),
('Piper excelsum - kawakawa5.jpg', 178, 1),
('Pittosporum crassifolium - karo.jpg', 179, 1),
('Pittosporum crassifolium - karo2.jpg', 179, 1),
('Pittosporum crassifolium - karo3.jpg', 179, 1),
('Pittosporum crassifolium - karo4.jpg', 179, 1),
('Pittosporum crassifolium - karo5.jpg', 179, 1),
('Pittosporum eugenioides - lemonwood or tarata.jpg', 180, 1),
('Pittosporum eugenioides - lemonwood or tarata2.jpg', 180, 1),
('Pittosporum eugenioides - lemonwood or tarata3.jpg', 180, 1),
('Pittosporum eugenioides - lemonwood or tarata4.jpg', 180, 1),
('Pittosporum eugenioides - lemonwood or tarata5.jpg', 180, 1),
('Pittosporum patulum - Pitpat.jpg', 181, 1),
('Pittosporum tenuifolium - kohuhu or black matipo.jpg', 182, 1),
('Pittosporum tenuifolium - kohuhu or black matipo2.jpg', 182, 1),
('Pittosporum tenuifolium - kohuhu or black matipo3.jpg', 182, 1),
('Pittosporum tenuifolium - kohuhu or black matipo4.jpg', 182, 1),
('Pittosporum tenuifolium - kohuhu or black matipo5.jpg', 182, 1),
('Pittosporum tenuifolium _Sumo_ - dwarf pittosporum.jpg', 183, 1),
('Pittosporum tenuifolium _Sumo_ - dwarf pittosporum2.jpg', 183, 1),
('Plagianthus divarivatus - swamp ribbonwood.jpeg', 184, 1),
('Plagianthus divarivatus - swamp ribbonwood2.jpg', 184, 1),
('Plagianthus divarivatus - swamp ribbonwood3.jpg', 184, 1),
('Plagianthus regius - lowland ribbonwood.jpeg', 185, 1),
('Plagianthus regius - lowland ribbonwood2.jpeg', 185, 1),
('Plagianthus regius - lowland ribbonwood3.jpeg', 185, 1),
('Plagianthus regius - lowland ribbonwood4.jpeg', 185, 1),
('Plagianthus regius - lowland ribbonwood5.jpg', 185, 1),
('Plagianthus regius - lowland ribbonwood6.jpg', 185, 1),
('Plagianthus regius - lowland ribbonwood7.jpeg', 185, 1),
('Platanus orientalis _Digitata_ - cut leaf plane.jpg', 186, 1),
('Platanus orientalis _Digitata_ - cut leaf plane2.jpg', 186, 1),
('Platanus orientalis _Digitata_ - cut leaf plane3.jpg', 186, 1),
('Platanus orientalis _Digitata_ - cut leaf plane4.jpg', 186, 1),
('Platanus orientalis _Digitata_ - cut leaf plane5.jpeg', 186, 1),
('Platanus orientalis _Digitata_ - cut leaf plane6.jpg', 186, 1),
('Platanus x acerifolia - London plane.jpg', 187, 1),
('Platanus x acerifolia - London plane2.jpg', 187, 1),
('Platanus x acerifolia - London plane3.jpg', 187, 1),
('Platanus x acerifolia - London plane4.jpg', 187, 1),
('Platanus x acerifolia - London plane5.jpg', 187, 1),
('Platanus x acerifolia - London plane6.jpg', 187, 1),
('Poa cita - silver tussock.jpeg', 188, 1),
('Poa cita - silver tussock2.jpg', 188, 1),
('Podocarpus laetus - mountain or Hall_s totara.jpg', 189, 1),
('Podocarpus laetus - mountain or Hall_s totara2.jpg', 189, 1),
('Podocarpus laetus - mountain or Hall_s totara3.jpg', 189, 1),
('Podocarpus nivalis - snow or mountain totara.jpg', 190, 1),
('Podocarpus nivalis - snow or mountain totara2.jpg', 190, 1),
('Podocarpus totara - totara.jpg', 191, 1),
('Podocarpus totara - totara2.jpg', 191, 1),
('Podocarpus totara - totara3.jpg', 191, 1),
('Polyspora axillaris - fried egg plant.jpeg', 192, 1),
('Polyspora axillaris - fried egg plant2.jpg', 192, 1),
('Polyspora axillaris - fried egg plant3.jpg', 192, 1),
('Polyspora axillaris - fried egg plant4.jpeg', 192, 1),
('Polystichum vestitum - prickly shield fern or puniu.jpg', 193, 1),
('Polystichum vestitum - prickly shield fern or puniu2.jpg', 193, 1),
('Polystichum vestitum - prickly shield fern or puniu3.jpg', 193, 1),
('Polystichum vestitum - prickly shield fern or puniu4.jpg', 193, 1),
('Polystichum vestitum - prickly shield fern or puniu5.jpg', 193, 1),
('Polystichum vestitum - prickly shield fern or puniu6.jpg', 193, 1),
('Polystichum vestitum - prickly shield fern or puniu7.jpg', 193, 1),
('Polystichum vestitum - prickly shield fern or puniu8.jpg', 193, 1),
('Populus trichocarpa - black cottonwood.jpeg', 194, 1),
('Populus trichocarpa - black cottonwood2.jpeg', 194, 1),
('Populus trichocarpa - black cottonwood3.jpeg', 194, 1),
('Populus trichocarpa - black cottonwood4.jpg', 194, 1),
('Populus trichocarpa - black cottonwood5.jpeg', 194, 1),
('Pratia (syn. Lobelia) angulata - panakenake.jpeg', 195, 1),
('Pratia (syn. Lobelia) angulata - panakenake2.jpeg', 195, 1),
('Pratia (syn. Lobelia) angulata - panakenake3.jpeg', 195, 1),
('Pratia (syn. Lobelia) angulata - panakenake4.jpeg', 195, 1),
('Pratia (syn. Lobelia) angulata - panakenake5.jpeg', 195, 1),
('Protea neriifolia - oleanderleaf protea.jpg', 196, 1),
('Protea neriifolia - oleanderleaf protea2.jpg', 196, 1),
('Protea neriifolia - oleanderleaf protea3.jpg', 196, 1),
('Protea neriifolia - oleanderleaf protea4.jpg', 196, 1),
('Protea neriifolia - oleanderleaf protea5.jpg', 196, 1),
('Protea neriifolia - oleanderleaf protea6.jpg', 196, 1),
('Protea neriifolia - oleanderleaf protea7.jpg', 196, 1),
('Protea neriifolia - oleanderleaf protea8.jpg', 196, 1),
('Prumnopitys taxifolia - matai.jpg', 197, 1),
('Prumnopitys taxifolia - matai2.jpg', 197, 1),
('Prumnopitys taxifolia - matai3.jpg', 197, 1),
('Prumnopitys taxifolia - matai4.jpg', 197, 1),
('Prumnopitys taxifolia - matai5.jpg', 197, 1),
('Prumnopitys taxifolia - matai6.png', 197, 1),
('Prumnopitys taxifolia - matai7.png', 197, 1),
('Prumnopitys taxifolia - matai8.png', 197, 1),
('Prunus laurocerasus - cherry laurel.jpg', 198, 1),
('Prunus laurocerasus - cherry laurel2.jpg', 198, 1),
('Prunus laurocerasus - cherry laurel3.jpg', 198, 1),
('Prunus laurocerasus - cherry laurel4.jpeg', 198, 1),
('Prunus laurocerasus - cherry laurel5.jpeg', 198, 1),
('Prunus laurocerasus - cherry laurel6.jpeg', 198, 1),
('Prunus laurocerasus - cherry laurel7.jpeg', 198, 1),
('Prunus laurocerasus - cherry laurel8.jpeg', 198, 1),
('Prunus lusitanica - Portuguese Cherry Laurel.jpg', 199, 1),
('Prunus lusitanica - Portuguese Cherry Laurel2.jpg', 199, 1),
('Prunus lusitanica - Portuguese Cherry Laurel3.jpg', 199, 1),
('Prunus lusitanica - Portuguese Cherry Laurel4.jpg', 199, 1),
('Prunus lusitanica - Portuguese Cherry Laurel5.jpg', 199, 1),
('Prunus x yedoensis - Yoshino cherry.jpg', 200, 1),
('Prunus x yedoensis - Yoshino cherry2.jpg', 200, 1),
('Prunus x yedoensis - Yoshino cherry3.jpg', 200, 1),
('Prunus x yedoensis - Yoshino cherry4.jpg', 200, 1),
('Prunus x yedoensis - Yoshino cherry5.jpg', 200, 1),
('Prunus x yedoensis - Yoshino cherry6.jpg', 200, 1),
('Prunus x yedoensis - Yoshino cherry7.jpg', 200, 1),
('Prunus x yedoensis - Yoshino cherry8.jpg', 200, 1),
('Pseudopanax crassifolius - lancewood.jpg', 201, 1),
('Pseudopanax crassifolius - lancewood2.jpg', 201, 1),
('Pseudopanax crassifolius - lancewood3.jpg', 201, 1),
('Pseudopanax crassifolius - lancewood4.jpg', 201, 1),
('Pseudopanax crassifolius - lancewood5.jpg', 201, 1),
('Pseudopanax crassifolius - lancewood6.jpg', 201, 1),
('Pseudopanax ferox - fierce lancewood.jpg', 202, 1),
('Pseudopanax ferox - fierce lancewood2.jpg', 202, 1),
('Pseudopanax ferox - fierce lancewood3.jpg', 202, 1),
('Pseudopanax lessonii - houpara.jpg', 203, 1),
('Pseudopanax lessonii - houpara2.jpg', 203, 1),
('Pseudopanax lessonii - houpara3.jpg', 203, 1),
('Pseudopanax lessonii - houpara4.jpg', 203, 1),
('Pseudowintera colorata - horopito or pepper tree.jpg', 204, 1),
('Pseudowintera colorata - horopito or pepper tree2.jpg', 204, 1),
('Pseudowintera colorata - horopito or pepper tree3.jpg', 204, 1),
('Pseudowintera colorata - horopito or pepper tree4.jpg', 204, 1),
('Pseudowintera colorata - horopito or pepper tree5.jpg', 204, 1),
('Pyrus communis - common pear.jpg', 205, 1),
('Pyrus communis - common pear2.jpg', 205, 1),
('Pyrus communis - common pear3.jpg', 205, 1),
('Pyrus communis - common pear4.jpg', 205, 1),
('Pyrus communis - common pear5.jpg', 205, 1),
('Pyrus communis - common pear6.jpg', 205, 1),
('Pyrus communis - common pear7.jpg', 205, 1),
('Pyrus communis - common pear8.jpg', 205, 1),
('Pyrus communis - common pear9.jpg', 205, 1),
('Pyrus communis - common pear10.jpg', 205, 1),
('Pyrus communis - common pear11.jpg', 205, 1),
('Pyrus communis - common pear12.jpeg', 205, 1),
('Quercus palustris - pin oak.jpg', 206, 1),
('Quercus palustris - pin oak2.jpg', 206, 1),
('Quercus palustris - pin oak3.jpg', 206, 1),
('Quercus palustris - pin oak4.jpg', 206, 1),
('Quercus robur - English oak.jpg', 207, 1),
('Quercus robur - English oak2.jpg', 207, 1),
('Quercus robur - English oak3.jpg', 207, 1),
('Quercus robur - English oak4.jpg', 207, 1),
('Quercus robur - English oak5.jpg', 207, 1),
('Quercus robur - English oak6.jpg', 207, 1),
('Quercus rubra - red oak.jpg', 208, 1),
('Quercus rubra - red oak2.jpg', 208, 1),
('Quercus rubra - red oak3.jpg', 208, 1),
('Quercus rubra - red oak4.jpg', 208, 1),
('Quercus rubra - red oak5.jpg', 208, 1),
('Quercus rubra - red oak6.jpg', 208, 1),
('Quercus rubra - red oak7.jpg', 208, 1),
('Quercus rubra - red oak8.jpg', 208, 1),
('Quercus rubra - red oak9.jpg', 208, 1),
('Rhododendron sp. - azalea.jpg', 209, 1),
('Rhododendron sp. - azalea2.jpg', 209, 1),
('Rhododendron sp. - azalea3.jpg', 209, 1),
('Rhododendron sp. - azalea4.jpg', 209, 1),
('Rhododendron sp. - azalea5.jpg', 209, 1),
('Rhododendron sp. - azalea6.jpg', 209, 1),
('Rhododendron sp. - rhododendron.jpeg', 210, 1),
('Rhopalostylis sapida - nikau palm.jpeg', 211, 1),
('Rhopalostylis sapida - nikau palm2.jpeg', 211, 1),
('Rhopalostylis sapida - nikau palm3.jpg', 211, 1),
('Rhopalostylis sapida - nikau palm4.jpg', 211, 1),
('Rhopalostylis sapida - nikau palm5.jpeg', 211, 1),
("Robinia pseudoacacia 'Lace Lady' - contoured black locust.jpeg", 212, 1),
("Robinia pseudoacacia 'Lace Lady' - contoured black locust2.jpeg", 212, 1),
("Robinia pseudoacacia 'Lace Lady' - contoured black locust3.jpeg", 212, 1),
('Rosa sp. _Ivey Hall_ - yellow floribunda rose.jpeg', 213, 1),
('Rosa sp. _Ivey Hall_ - yellow floribunda rose2.jpeg', 213, 1),
('Rosmarinus officinalis - rosemary.jpg', 214, 1),
('Rosmarinus officinalis - rosemary2.jpg', 214, 1),
('Rosmarinus officinalis - rosemary3.jpg', 214, 1),
('Rosmarinus officinalis - rosemary4.jpeg', 214, 1),
('Rosmarinus officinalis - rosemary5.jpg', 214, 1),
('Rosmarinus officinalis - rosemary6.jpg', 214, 1),
('Rosmarinus officinalis - rosemary7.jpeg', 214, 1),
('Rosmarinus officinalis - rosemary8.jpeg', 214, 1),
('Rubus cissoides - bush lawyer.jpg', 215, 1),
('Rubus cissoides - bush lawyer2.jpg', 215, 1),
('Rubus cissoides - bush lawyer3.jpg', 215, 1),
('Salvia officinalis - common sage.jpeg', 216, 1),
('Salvia officinalis - common sage2.jpg', 216, 1),
('Salvia officinalis - common sage3.jpg', 216, 1),
('Salvia officinalis - common sage4.jpeg', 216, 1),
('Salvia officinalis - common sage5.jpg', 216, 1),
('Salvia officinalis - common sage6.jpg', 216, 1),
('Salvia officinalis - common sage7.jpeg', 216, 1),
('Salvia officinalis - common sage8.jpg', 216, 1),
('Salvia officinalis - common sage9.jpg', 216, 1),
('Santolina chamaecyparissus - lavender cotton.jpg', 217, 1),
('Santolina chamaecyparissus - lavender cotton2.jpg', 217, 1),
('Santolina chamaecyparissus - lavender cotton3.jpg', 217, 1),
('Santolina chamaecyparissus - lavender cotton4.jpg', 217, 1),
('Santolina chamaecyparissus - lavender cotton5.jpg', 217, 1),
('Santolina chamaecyparissus - lavender cotton6.jpg', 217, 1),
('Sarcococca confusa - sweet box.jpg', 218, 1),
('Sarcococca confusa - sweet box2.jpg', 218, 1),
('Sarcococca confusa - sweet box3.jpg', 218, 1),
('Sarcococca confusa - sweet box4.jpg', 218, 1),
('Sarcococca confusa - sweet box5.jpg', 218, 1),
('Sarcococca confusa - sweet box6.jpg', 218, 1),
('Sarcococca confusa - sweet box7.jpeg', 218, 1),
('Sarcococca confusa - sweet box8.jpg', 218, 1),
('Sarcococca confusa - sweet box9.jpg', 218, 1),
('Scleranthus biflorus - knawel cushion or cushion plant.jpg', 219, 1),
('Scleranthus biflorus - knawel cushion or cushion plant2.jpg', 219, 1),
('Scleranthus biflorus - knawel cushion or cushion plant3.jpg', 219, 1),
('Scleranthus biflorus - knawel cushion or cushion plant4.jpeg', 219, 1),
('Sedum spectabile _Autumn Joy_ - stonecrop.jpg', 220, 1),
('Sedum spectabile _Autumn Joy_ - stonecrop2.jpg', 220, 1),
('Sedum spectabile _Autumn Joy_ - stonecrop3.jpg', 220, 1),
('Sedum spectabile _Autumn Joy_ - stonecrop4.jpg', 220, 1),
('Sedum spectabile _Autumn Joy_ - stonecrop5.jpg', 220, 1),
('Sedum spectabile _Autumn Joy_ - stonecrop6.jpg', 220, 1),
('Sedum spectabile _Autumn Joy_ - stonecrop7.jpg', 220, 1),
('Sequoia sempervirens - redwood.jpg', 221, 1),
('Sequoia sempervirens - redwood2.jpg', 221, 1),
('Sequoia sempervirens - redwood3.jpg', 221, 1),
('Sequoia sempervirens - redwood4.jpg', 221, 1),
('Sequoia sempervirens - redwood5.jpeg', 221, 1),
('Sequoia sempervirens - redwood6.jpg', 221, 1),
("Skimmia japonica - Japanese skimmia.jpg", 222, 1),
("Skimmia japonica - Japanese skimmia2.jpg", 222, 1),
("Skimmia japonica - Japanese skimmia3.jpg", 222, 1),
("Skimmia japonica - Japanese skimmia4.jpg", 222, 1),
('Solanum laciniatum - poroporo.jpg', 223, 1),
('Solanum laciniatum - poroporo2.jpg', 223, 1),
('Solanum laciniatum - poroporo3.jpg', 223, 1),
('Solanum laciniatum - poroporo4.jpg', 223, 1),
('Solanum laciniatum - poroporo5.jpg', 223, 1),
('Sophora microphylla - South Island kowhai.jpg', 224, 1),
('Sophora microphylla - South Island kowhai2.jpg', 224, 1),
('Sophora microphylla - South Island kowhai3.jpg', 224, 1),
('Sophora microphylla - South Island kowhai4.jpg', 224, 1),
('Sophora microphylla - South Island kowhai5.jpg', 224, 1),
('Sophora microphylla - South Island kowhai6.jpg', 224, 1),
('Sophora microphylla - South Island kowhai7.jpg', 224, 1),
('Sophora molloyi _Dragons Gold_ - Cook Strait kowhai.jpg', 225, 1),
('Sophora molloyi _Dragons Gold_ - Cook Strait kowhai2.jpg', 225, 1),
('Sophora molloyi _Dragons Gold_ - Cook Strait kowhai3.jpg', 225, 1),
('Sophora molloyi _Dragons Gold_ - Cook Strait kowhai4.jpg', 225, 1),
('Sophora prostrata - prostrate kowhai.jpg', 226, 1),
('Sophora prostrata - prostrate kowhai2.jpeg', 226, 1),
('Sophora prostrata - prostrate kowhai3.jpg', 226, 1),
('Sophora prostrata - prostrate kowhai4.jpg', 226, 1),
('Sophora prostrata - prostrate kowhai5.jpg', 226, 1),
('Sophora prostrata - prostrate kowhai6.jpg', 226, 1),
('Sophora prostrata - prostrate kowhai7.jpg', 226, 1),
('Sophora prostrata - prostrate kowhai8.jpg', 226, 1),
('Sophora tetraptera - North Island kowhai.jpg', 227, 1),
('Sophora tetraptera - North Island kowhai2.jpg', 227, 1),
('Sophora tetraptera - North Island kowhai3.jpg', 227, 1),
('Sophora tetraptera - North Island kowhai4.jpg', 227, 1),
('Sorbus aucuparia - rowan.jpg', 228, 1),
('Sorbus aucuparia - rowan2.jpg', 228, 1),
('Sorbus aucuparia - rowan3.jpg', 228, 1),
('Sorbus aucuparia - rowan4.jpg', 228, 1),
('Sorbus aucuparia - rowan5.jpg', 228, 1),
('Sorbus aucuparia - rowan6.jpg', 228, 1),
('Sorbus aucuparia - rowan7.jpg', 228, 1),
('Teucridium parvifolium - teucridium.jpg', 229, 1),
('Teucridium parvifolium - teucridium2.jpeg', 229, 1),
('Teucridium parvifolium - teucridium3.jpeg', 229, 1),
('Teucridium parvifolium - teucridium4.jpeg', 229, 1),
('Teucridium parvifolium - teucridium5.jpeg', 229, 1),
('Teucridium parvifolium - teucridium6.jpeg', 229, 1),
('Tilia cordata - lime tree.jpeg', 230, 1),
('Tilia cordata - lime tree2.jpeg', 230, 1),
('Tilia cordata - lime tree3.jpeg', 230, 1),
('Tilia cordata - lime tree4.jpeg', 230, 1),
('Tilia cordata - lime tree5.jpeg', 230, 1),
('Tilia cordata - lime tree6.jpeg', 230, 1),
('Tilia vulgaris - Lime Tree.jpg', 231, 1),
('Tilia vulgaris - Lime Tree2.jpeg', 231, 1),
('Tilia vulgaris - Lime Tree3.jpg', 231, 1),
("Trachycarpus fortunei - Chinese Windmill Palm.jpg", 232, 1),
("Trachycarpus fortunei - Chinese Windmill Palm2.jpg", 232, 1),
('Typha orientalis - raupo or bullrush.jpg', 233, 1),
('Typha orientalis - raupo or bullrush2.jpg', 233, 1),
('Typha orientalis - raupo or bullrush3.jpg', 233, 1),
('Typha orientalis - raupo or bullrush4.jpg', 233, 1),
('Typha orientalis - raupo or bullrush5.jpg', 233, 1),
('Typha orientalis - raupo or bullrush6.jpg', 233, 1),
('Typha orientalis - raupo or bullrush7.jpg', 233, 1),
('Ulmus carpinifolia _Variegata_ - variegated elm.jpg', 234, 1),
('Ulmus carpinifolia _Variegata_ - variegated elm2.jpg', 234, 1),
('Ulmus carpinifolia _Variegata_ - variegated elm3.jpg', 234, 1),
('Ulmus carpinifolia _Variegata_ - variegated elm4.webp', 234, 1),
('Veronica _Emerald Green_ - Whipcord Hebe.jpg', 235, 1),
('Veronica _Emerald Green_ - Whipcord Hebe2.jpg', 235, 1),
('Veronica _Emerald Green_ - Whipcord Hebe3.jpg', 235, 1),
('Veronica hulkeana - New Zeland lilac.jpeg', 236, 1),
('Veronica hulkeana - New Zeland lilac2.jpeg', 236, 1),
('Veronica hulkeana - New Zeland lilac3.jpeg', 236, 1),
('Veronica hulkeana - New Zeland lilac4.jpeg', 236, 1),
('Veronica hulkeana - New Zeland lilac5.jpg', 236, 1),
('Veronica odora _Prostrata_ - prostrate hebe.jpg', 237, 1),
('Veronica odora _Prostrata_ - prostrate hebe2.jpg', 237, 1),
('Veronica salicifolia - Koromiko.jpg', 238, 1),
('Veronica salicifolia - Koromiko2.jpg', 238, 1),
('Veronica salicifolia - Koromiko3.jpg', 238, 1),
('Veronica salicifolia - Koromiko4.jpg', 238, 1),
('Veronica salicifolia - Koromiko5.jpg', 238, 1),
('Veronica sp. _Wiri MIst_ - wiri mist hebe.jpeg', 239, 1),
('Veronica sp. _Wiri MIst_ - wiri mist hebe2.jpeg', 239, 1),
('Veronica sp. _Wiri MIst_ - wiri mist hebe3.jpeg', 239, 1),
('Veronica sp. _Wiri MIst_ - wiri mist hebe4.jpeg', 239, 1),
('Veronica sp. _Wiri MIst_ - wiri mist hebe5.jpeg', 239, 1),
('Veronica speciosa  - large leaved hebe.jpg', 240, 1),
('Veronica speciosa  - large leaved hebe2.jpg', 240, 1),
('Veronica speciosa  - large leaved hebe3.jpg', 240, 1),
('Veronica speciosa  - large leaved hebe4.jpg', 240, 1),
('Veronica topiaria - topiary hebe.jpg', 241, 1),
('Veronica topiaria - topiary hebe2.jpg', 241, 1),
('Veronica topiaria - topiary hebe3.jpg', 241, 1),
('Veronica topiaria - topiary hebe4.jpg', 241, 1),
('Veronica topiaria - topiary hebe5.jpg', 241, 1),
('Veronica topiaria - topiary hebe6.jpg', 241, 1),
('Viburnum japonicum - Japanese Viburnum.jpg', 242, 1),
('Viburnum japonicum - Japanese Viburnum2.jpg', 242, 1),
('Viburnum japonicum - Japanese Viburnum3.jpeg', 242, 1),
('Viburnum japonicum - Japanese Viburnum4.jpeg', 242, 1),
('Viburnum japonicum - Japanese Viburnum5.jpg', 242, 1),
('Viburnum japonicum - Japanese Viburnum6.jpg', 242, 1),
('Viburnum japonicum - Japanese Viburnum7.jpg', 242, 1),
('Viburnum tinus - laurustinus.jpg', 243, 1),
('Viburnum tinus - laurustinus2.jpg', 243, 1),
('Viburnum tinus - laurustinus3.jpeg', 243, 1),
('Viburnum tinus - laurustinus4.jpeg', 243, 1),
('Viburnum tinus - laurustinus5.jpg', 243, 1),
('Viburnum tinus - laurustinus6.jpg', 243, 1),
('Viburnum tinus - laurustinus7.jpg', 243, 1),
('Viburnum tinus - laurustinus8.jpeg', 243, 1),
('Viburnum tinus - laurustinus9.jpg', 243, 1),
('Viburnum tinus - laurustinus10.jpg', 243, 1),
('Viburnum tinus - laurustinus11.jpg', 243, 1),
('Wisteria sinensis - Chinese wisteria.jpg', 244, 1),
('Wisteria sinensis - Chinese wisteria2.jpeg', 244, 1),
('Wisteria sinensis - Chinese wisteria3.jpeg', 244, 1),
('Wisteria sinensis - Chinese wisteria4.jpg', 244, 1),
('Wisteria sinensis - Chinese wisteria5.jpg', 244, 1),
('Wisteria sinensis - Chinese wisteria6.png', 244, 1),
('Wisteria sinensis - Chinese wisteria7.jpg', 244, 1),
('Zantedeschia aethiopica - arum or calla Lily.jpeg', 245, 1),
('Zantedeschia aethiopica - arum or calla Lily2.jpg', 245, 1),
('Zantedeschia aethiopica - arum or calla Lily3.jpg', 245, 1),
('Zantedeschia aethiopica - arum or calla Lily4.jpeg', 245, 1),
('Zantedeschia aethiopica - arum or calla Lily5.jpg', 245, 1),
('Zantedeschia aethiopica - arum or calla Lily6.jpeg', 245, 1);

INSERT INTO product_type (type_name, is_active) VALUES
('Plant', 1),
('Ground', 1),
('Other', 1);

INSERT INTO product (product_name, product_type, price, picture, is_active) VALUES
('Agapanthus africanus', 1, 100, 'Agapanthus_africanus.png', 1),
('Aguilegia', 1, 100, 'Aguilegia.png', 1),
('Argyranthemum frutescens', 1, 100, 'Argyranthemum_frutescens.png', 1),
('Astilbe chinensis', 1, 100, 'Astilbe_chinensis.png', 1),
('Bougainvillea', 1, 100, 'Bougainvillea.png', 1),
('Bridal Wreath', 1, 100, 'Bridal_Wreath.png', 1),
('Campanula medium -- blue', 1, 100, 'Campanula_medium_--_blue.png', 1),
('Campanula medium -- pink', 1, 100, 'Campanula_medium_--_pink.png', 1),
('Campanula punctata Lam', 1, 100, 'Campanula_punctata_Lam.png', 1),
('Cyclamen persicum', 1, 100, 'Cyclamen_persicum.png', 1),
('Dahlia pinnata Cav', 1, 100, 'Dahlia_pinnata_Cav.png', 1),
('Delphinium', 1, 100, 'Delphinium.png', 1),
('Digitalis purpurea', 1, 100, 'Digitalis_purpurea.png', 1),
('Elephant Ears', 1, 100, 'Elephant_Ears.png', 1),
('Eupatorium fortunei', 1, 100, 'Eupatorium_fortunei.png', 1),
('Evening Primrose', 1, 100, 'Evening_Primrose.png', 1),
('Golden Foster Holly', 1, 100, 'Golden_Foster_Holly.png', 1),
('Hamamelis mollis', 1, 100, 'Hamamelis_mollis.png', 1),
('Helichrysum petiolare', 1, 100, 'Helichrysum_petiolare.png', 1),
('Hydrangea macrophylla', 1, 100, 'Hydrangea_macrophylla.png', 1),
('Ipomoea nil', 1, 100, 'Ipomoea_nil.png', 1),
('Lamprocapnos spectabilis', 1, 100, 'Lamprocapnos_spectabilis.png', 1),
('Lavender', 1, 100, 'Lavender.png', 1),
('Lily', 1, 100, 'Lily.png', 1),
('Lupinus', 1, 100, 'Lupinus.png', 1),
('Maple', 1, 100, 'Maple.png', 1),
('Matteuccia struthiopteris', 1, 100, 'Matteuccia_struthiopteris.png', 1),
('Myosotis', 1, 100, 'Myosotis.png', 1),
('Parthenocissus tricuspidata', 1, 100, 'Parthenocissus_tricuspidata.png', 1),
('Pelargonium hortorum Bailey', 1, 100, 'Pelargonium_hortorum_Bailey.png', 1),
('Phlox drummondii', 1, 100, 'Phlox_drummondii.png', 1),
('Purple coneflower', 1, 100, 'Purple_coneflower.png', 1),
('Rainlily', 1, 100, 'Rainlily.png', 1),
('Salvia japonica', 1, 100, 'Salvia_japonica.png', 1),
('Stipa capillata', 1, 100, 'Stipa_capillata.png', 1),
('Strelitzia reginae', 1, 100, 'Strelitzia_reginae.png', 1),
('Tulip', 1, 100, 'Tulip.png', 1),
('Verbena officinalis', 1, 100, 'Verbena_officinalis.png', 1),
('Viburnum hanceanum Maxim', 1, 100, 'Viburnum_hanceanum_Maxim.png', 1),
('Vitex agnus-castus', 1, 100, 'Vitex_agnus-castus.png', 1),
('Grass', 2, 100, 'grass.jpg', 1),
('Road', 2, 100, 'road.jpg', 1),
('Water', 2, 100, 'water.jpg', 1);
